% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  a4paper,
  abstract=true]{scrartcl}
\usepackage{xcolor}
\usepackage[top=30mm,left=30mm,right=30mm,heightrounded]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


% TODO: Add custom LaTeX header directives here
\usepackage{float, booktabs, siunitx, orcidlink, pdfpages, scrlayer-scrpage}
\setkomafont{disposition}{\bfseries}
\providecommand{\keywords}[1]
{
  \small	
  \textbf
{\textit{Keywords---}} #1
}
\newcommand\blfootnote[1]{%
  \begingroup

  \renewcommand\thefootnote{}\footnote{#1}%
  \addtocounter{footnote}{-1}%
  \endgroup }
\usepackage{float}
\usepackage{tabularray}
\usepackage[normalem]{ulem}
\usepackage{graphicx}
\usepackage{rotating}
\UseTblrLibrary{siunitx}
\NewTableCommand{\tinytableDefineColor}[3]{\definecolor{#1}{#2}{#3}}
\newcommand{\tinytableTabularrayUnderline}[1]{\underline{#1}}
\newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
\newcommand{\centerstart}{\begin{center}}
\newcommand{\centerend}{\end{center}}
\usepackage[makeroom]{cancel}
\usepackage{pgfplots, comment}
\usepackage{amsthm, thm-restate}
\declaretheorem[name=Proposition]{prp}
\newtheorem{asp}{Assumption}
\theoremstyle{definition}
\newtheorem{defi}{Definition}
\newtheorem{hyp}{Hypothesis}
\newtheorem{subhyp}{Hypothesis}[hyp]
\renewcommand{\thesubhyp}{\thehyp\alph{subhyp}}
\usetikzlibrary{math}
\usepackage{codehigh}
\UseTblrLibrary{booktabs}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Bail out the money printer?},
  pdfkeywords={Central Bank Losses, Fiscal-Monetary Interaction, Public
Finance},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Bail out the money printer?}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{The impact of fiscal indemnity on central bank profitability}
\author{Dianyi Yang~\orcidlink{0009-0004-4652-3429}\textsuperscript{1}}
\date{07 February 2026}
\begin{document}
\pagenumbering{roman}
\maketitle
%TC:ignore
\begin{abstract}
Since 2022, central bank losses have been prevalent in advanced
economies due to previous quantitative easing and recent inflationary
pressures. This paper focuses on the unique case of the United Kingdom,
where the government promised in advance to cover any central bank
losses arising from quantitative easing. This promise is known as the
indemnity. A game-theoretical model is proposed to explain the causes
and effects of such indemnity. The model's predictions about the
indemnity's effect on central bank profitability are empirically
examined. Using the novel Dynamic Multilevel Latent Factor Model
(DM-LFM), the indemnity is found to have significantly boosted the Bank
of England's profits in the deflationary environment after 2008, but
exacerbated its losses under the recent inflationary pressure since
2022. The theoretical model suggests the pronounced effects are due to
the Bank of England's high sensitivity to losses and the UK government's
moderate fiscal liberalism. Therefore, the British experience should not
be generalised. Nevertheless, the theoretical and empirical lessons can
inform policy-makers about future institutional designs concerning the
fiscal-monetary interactions and the public finance-price stability
trade-off.
\end{abstract}
\begin{center}
\keywords{Central Bank Losses, Fiscal-Monetary Interaction, Public
Finance}
\end{center}

\blfootnote{I would like to express my most sincere gratitude to my
supervisor, Dr David Foster, for his exceptional responsiveness,
patience, and unwavering support throughout the course of this research.
I would also like to thank Dr David Woordruff for his invaluable
discussions on this niche topic and for generously sharing relevant
literature that greatly informed and enriched my research. All errors
are my own. Replication files for this project are available on
\href{https://github.com/kv9898/BailoutCB}{GitHub}.}

%TC:endignore



\setstretch{1.5}
\textsuperscript{1} London School of Economics and Political Science

\newpage

\section{Introduction}\label{introduction}

\pagenumbering{arabic}
\setcounter{page}{1}

Large financial losses incurred by central banks were once considered
theoretically improbable in advanced economies due to the stable profit
generated from the monopolistic supply of currency, known as the
seigniorage (\citeproc{ref-Cukierman2011}{Cukierman, 2011, pp. 44--45};
\citeproc{ref-theevol1991}{Downes \& Vaez-Zadeh, 1991};
\citeproc{ref-Stella2005}{Stella, 2005}). Nevertheless, since 2022,
central bank losses have become more common due to the compound effect
of

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  higher interest rates implemented to tackle the inflationary pressure
  following COVID-19 and the Russo-Ukrainian War, and
\item
  the large central bank balance sheets resulting from previous
  Quantitative Easing (QE) (\citeproc{ref-Cecchetti2024}{Cecchetti \&
  Hilscher, 2024}).
\end{enumerate}

Major Western economies such as the US, Eurozone and UK introduced QE as
a novel form of monetary policy to combat the deflationary pressure from
the recession following the 2007-2008 Global Financial Crisis (GFC)
(\citeproc{ref-Joyce2012}{Joyce et al., 2012}). Traditionally, central
banks aim to achieve low and stable inflation (typically 2\%) by setting
short-term interest rates. Nevertheless, one obvious drawback of this
instrument is that the market interest rates cannot possibly approach
zero - this limitation is known as the zero lower bound. After the GFC,
inflation was so low that the problem of zero lower bound materialised.
Consequently, central banks initiated massive asset purchases (primarily
long-term government bonds), aiming to reduce \emph{long-term} interest
rates. The scale and pace of such purchases are \emph{ex ante} decided
by Monetary Policy Committees, hence the term Quantitative Easing (QE).

Due to the lack of any material inflationary threat and the sluggish
recovery from the recession, the assets purchased during QE were not
actively sold and interest rates were rarely raised. The returns on
these assets financed by cheap credit generated substantial profits for
central banks. These profits are usually remitted to their respective
governments (\citeproc{ref-Chaboud2013}{Chaboud \& Leahy, 2013}). At
this point, central bank capital and profitability received little
attention from researchers and policymakers
(\citeproc{ref-Cecchetti2024}{Cecchetti \& Hilscher, 2024}). However,
this euphoria ended in 2022 when the major central banks acknowledged
the long-term inflationary prospects arising from the COVID-19 supply
chain bottlenecks and the Russian invasion of Ukraine
(\citeproc{ref-Blanchard2023}{Blanchard \& Bernanke, 2023}). Monetary
policy was subsequently tightened: central banks raised the interest
rates they paid on commercial banks reserves and sold their assets at
discounted prices, turning previous profits into losses.

This paper seeks to explain the \emph{national variation} in central
bank losses (profits). Despite other determinants of central bank
financial stability such as sovereign defaults, exchange rates
(\citeproc{ref-Hall2015}{Hall \& Reis, 2015}) and accounting rules
(\citeproc{ref-Cecchetti2024}{Cecchetti \& Hilscher, 2024}), this paper
focuses specifically on one political and institutional factor: the
government's fiscal indemnity against QE-related losses of the central
bank.

The United Kingdom is unique among the advanced economies which adopted
QE after the GFC due to the indemnity arrangements between its treasury
and central bank, the Bank of England (BoE). In a letter from 29 January
2009\footnote{The letter was originally available at the UK
  \href{http://www.hm-treasury.gov.uk/d/ck_letter_boe290109.pdf}{Treasury}
  and
  \href{http://www.bankofengland.co.uk/markets/apfgovletter090129.pdf}{BoE}
  websites but was later removed. It is only accessible from the
  \href{https://webarchive.nationalarchives.gov.uk/ukgwa/+/http:/www.hm-treasury.gov.uk/d/ck_letter_boe290109.pdf}{National
  Archives} at the time of writing.}, the UK Treasury authorised the BoE
to create the Asset Purchase Facility (APF) which served as the central
bank's QE vehicle. The letter stipulates the size of the fund (initially
£50 billion), the eligible sterling assets to be purchased and the
\emph{explicit} guarantee that any financial losses incurred by the
facility would be compensated for by the government. This guarantee,
henceforth referred to as the \emph{indemnity}, forecloses the
possibility of a \emph{quid pro quo,} where the government leverages the
recapitalisation of a loss-making central bank for favourable monetary
policy (\citeproc{ref-Stella1997}{Stella, 1997}), a potential source of
political pressure faced by central banks under implicit loss-coverage
rules. In a subsequent exchange of letters in 2012\footnote{The exchange
  of letters are available from the
  \href{https://www.bankofengland.co.uk/letter/2012/apf-excess-letter-november-2012}{BoE
  website}.}, the Conservative government reaffirmed the indemnity
granted by their Labour predecessor and it was agreed that the profit
(losses) of the APF would be regularly transferred to (from) the
Treasury in cash.

As a result, the growing fiscal burden of the indemnity has become a
\emph{political} issue unique to the UK: since the Treasury began
compensating the APF for losses in 2022
(\citeproc{ref-ft-indem-start}{Financial Times, 2023b}), the expected
total bill faced by the Treasury was repeatedly revised upwards from £50
billion to a startling £150 billion (\citeproc{ref-ft150bn}{Financial
Times, 2023a}). More worryingly, the UK taxpayers are liable for these
losses without the right to know. In early 2024, the House of Lords
Economic Affairs Committee demanded that the full details of the
indemnity agreement be published. The request was \emph{refused} by the
Treasury due to `market sensitivities'
(\citeproc{ref-Bloomberg2024}{Bloomberg, 2024}). The House of Commons
Treasury Committee (\citeproc{ref-HCTC2024}{2024, para. 64}) concluded
in a report that ``there is no {[}\emph{ex post}{]} reason to think that
the indemnity and cashflow arrangements devised in 2009 and 2012 are the
most suitable available.'' A group of Conservative backbenchers went so
far as to demand a review of the BoE's independence.
(\citeproc{ref-Independent2024}{The Independent, 2024}).

Thus far, the British experience may resemble a familiar story of
\emph{moral hazard}, defined as a situation where an agent adopts
riskier behaviour if the risk can be entirely or partially transferred
to another party (\citeproc{ref-Landes2013}{Landes, 2013}). Indeed, even
Michael Saunders, a former member of the of the BoE Monetary Policy
Committee admitted that the Bank is incurring larger losses on QE than
other non-indemnified counterparts, because it has been taking
\emph{higher risks} by buying and selling longer-dated bonds
(\citeproc{ref-ft-admit-higher-losses}{Financial Times, 2023c})\emph{.}

Nevertheless, this paper argues that the moral hazard rationale does not
depict a full picture of the story, because many important questions
remain unanswered. If the indemnity arrangements were so unwise, why did
the UK government agree to it in the first place? Does a naive loss
comparison constitute a valid causal inference, free from selection
bias? Is the indemnity a necessary condition for stable inflation, as
the conventional economic theory prescribes
(\citeproc{ref-Hall2015}{Hall \& Reis, 2015})? More importantly, do
higher risks necessarily lead to higher losses and is the UK case
generalisable to other countries?

To address these difficult questions, this paper proposes a
game-theoretical model to examine post-2008 fiscal-monetary interactions
in the \hyperref[sec-theory]{Theory} section. Key theoretical
implications are as follows:

\begin{itemize}
\item
  The UK introduced the indemnity because of its government's relatively
  low fiscal conservatism.
\item
  Naive profit and loss comparisons likely \emph{underestimate} the
  impact of indemnity on BoE financials.
\item
  The model confirms the benefits of indemnity for price stability, but
  highlights the \emph{heterogeneity} in such benefits across contexts.
\item
  Indemnity leads to higher risk-taking by central banks, but higher
  risks only translate into higher losses

  \begin{enumerate}
  \def\labelenumi{\arabic{enumi}.}
  \item
    under inflationary pressure, and
  \item
    when the central bank's sensitivity to losses is not too low.
  \end{enumerate}

  Thus, the UK experience should \emph{not} be directly extrapolated to
  other contexts.
\item
  The effects of indemnity on profits under deflationary and
  inflationary pressures can be in \emph{opposite} directions.
\end{itemize}

Therefore, the impact of the indemnity on the BoE profits is estimated
separately for the deflationary (2009-2021) and inflationary (2022-2023)
periods. The \hyperref[sec-results]{findings} indicate the indemnity
boosted the profits in the former, and exacerbated the losses in the
latter for the British case. These results are robust to
\hyperref[sec-robustness]{additional checks}.

The remainder of this paper is organised as follows:
Section~\ref{sec-litreview} reviews the existing literature;
Section~\ref{sec-theory} sets out the game-theoretical framework to be
tested. Section~\ref{sec-data} describes the data used for empirical
analysis. Section~\ref{sec-empirical} introduces the main estimator
(DM-lFM) for causal inference. The main empirical results are presented
in Section~\ref{sec-results}, with their robustness examined in
Section~\ref{sec-robustness}. This is followed by a discussion on the
mapping of the countries to the theoretical domain
(Section~\ref{sec-discussion}) and the conclusion
(Section~\ref{sec-conclusion}).

\section{Literature Review}\label{sec-litreview}

Prior to 2008, the profits of central banks in mature economies tended
to be small and stable, which rarely intrigued scholars or were
typically discussed only as a secondary point. Downes \& Vaez-Zadeh
(\citeproc{ref-theevol1991}{1991}) provide a great summary of
\emph{pre-QE} central bank financials. Downes \& Vaez-Zadeh
(\citeproc{ref-theevol1991}{1991}) indicate that, when excluding the
impact of exchange rate fluctuations, as per the conventional accounting
standards for current profits, central bank profitability is mainly
attributable to \emph{seigniorage,} profits of the central bank
``resulting from its ability to purchase interest-bearing assets by
issuing non-interest-bearing high-powered money\footnote{Molho
  (\citeproc{ref-Molho1989}{1989}) reviews the debate around the exact
  measurement of seigniorage.}'' (p.78). More importantly, Downes \&
Vaez-Zadeh (\citeproc{ref-theevol1991}{1991}) point out that part of the
seigniorage is an \emph{inflation tax.} This highlights the possibility
that a non-indemnified central bank may connive in higher inflation to
finance its losses, a result echoed with our model in
Section~\ref{sec-theory}.

Due to the novelty of losses associated with QE, the existing empirical
literature centres on pre-QE central bank losses, which mostly occurred
in the \emph{developing and transition} economies
(\citeproc{ref-Beckerman1997}{Beckerman, 1997}); this contributes little
to the understanding of the recent QE-related losses in the advanced
economies. Dalton \& Dziobek (\citeproc{ref-Dalton2005}{2005}) attribute
such losses to monetary operations under extreme conditions and
financial sector restructuring, while others blame them on central
banks' engagement in \emph{quasi-fiscal} activities, which increases
central banks' expenditures (\citeproc{ref-Lonnberg2008}{Lonnberg \&
Stella, 2008}; \citeproc{ref-Mackenzie1996}{Mackenzie \& Stella, 1996};
\citeproc{ref-Markiewicz2001}{Markiewicz, 2001};
\citeproc{ref-Munoz2007}{Muñoz, 2007};
\citeproc{ref-Sweidan2011}{Sweidan, 2011}). Despite these cases of
losses, most central banks did not have specific rules to cover losses
(\citeproc{ref-theevol1991}{Downes \& Vaez-Zadeh, 1991};
\citeproc{ref-Pringle1999}{Pringle \& Turner, 1999}). This situation
improved after the GFC when specific rules such as the use of particular
buffers, claims on future profits, direct capitalisation and losses
carried forward have become more common (\citeproc{ref-Bunea2016}{Bunea
et al., 2016}).

This paper thus contributes to the growing body of literature on
\emph{advanced} economies that has flourished since the GFC. After the
GFC, unconventional monetary policies such as QE were introduced and
fundamentally changed the financial stability of central banks. In the
post-QE era, the threats to central bank profitability in mature
economies have shifted to the interest rate, default and exchange rate
risks (\citeproc{ref-Hall2015}{Hall \& Reis, 2015}). Furthermore, since
the GFC the literature has converged on a new definition of central bank
\emph{solvency}, namely the present value of the central bank's
\emph{dividends} to the treasury being non-negative, without which
hyper-inflation may result (\citeproc{ref-Bassetto2013}{Bassetto \&
Messer, 2013}; \citeproc{ref-DelNegro2015}{Del Negro \& Sims, 2015};
\citeproc{ref-Hilscher2015}{Hilscher et al., 2015};
\citeproc{ref-Reis2013}{Reis, 2013},
\citeproc{ref-Reis2015}{2015})\footnote{This definition is named
  ``intertemporal insolvency'' as the most accepted definition of the
  three definitions provided by Reis (\citeproc{ref-Reis2015}{2015}).}.
This is in stark contrast to the traditional emphasis on positive
\emph{equity} as the criterion for solvency, which inappropriately
treats central banks as commercial banks. The fact that central
banks\footnote{For example, Chile, Czechia, Hungary, Israel and Mexico.}
have historically fulfilled their duties withstanding extended periods
of losses and negative equity may \emph{mislead} the public into
thinking the financial performance of central banks does not matter at
all (\citeproc{ref-Bell2023}{Bell et al., 2023}).

According to this new definition, the only guarantee of central bank's
solvency and consequently, effective monetary policy, is a dividend rule
that requires the treasury to pay the central bank a ``negative
dividend'' (\citeproc{ref-Hall2015}{Hall \& Reis, 2015}). This
``negative dividend rule'' is perfectly epitomised by the indemnity
agreements between the UK Treasury and the Bank of England. Therefore,
there is a theoretical foundation for the UK indemnity arrangement as a
\emph{sufficient} condition for central bank solvency, which is in turn
a \emph{necessary} condition for achieving inflation targets. This
inflation-stabilising effect is also confirmed by our theoretical
analysis (see Proposition \ref{prp-stabinf}). However, the UK's negative
dividend rule is only one among many possible arrangements. Chaboud \&
Leahy (\citeproc{ref-Chaboud2013}{2013}) provide case studies into
central banks losses in advanced economies; Bunea et al.
(\citeproc{ref-Bunea2016}{2016}) categorize the profit distribution,
loss coverage and recapitalisation arrangements of central banks around
the world, while Long \& Fisher (\citeproc{ref-Long2024}{2024}) provide
the most detailed summary of such arrangements for \emph{most}
countries. Nevertheless, for simplicity we do not distinguish between
the non-indemnity arrangements in this paper, as central banks are still
more or less subject to loss-related pressure under these rules.

More importantly, the literature has identified central bank losses and
their coverage as \emph{political economy} problems. Hall \& Reis
(\citeproc{ref-Hall2015}{2015}) notice that a payment from the treasury
to the central bank involves the appropriation of government funds,
subject to the political process. Similarly, indemnity as an
\emph{unconditional commitment} to such appropriation is ultimately a
\emph{political} decision. Goncharov et al.
(\citeproc{ref-Goncharov2023}{2023}) document the central banks'
tendency to report small profits rather than losses, driven by political
factors such as public opinion and governor reappointability. Diessner
(\citeproc{ref-Diessner2023}{2023}) explore the case studies of the UK,
Japan and Eurozone, and reach a similar conclusion - that central
bankers' aversion to losses despite their ability to create currency is
associated with their pursuit of \emph{independence} from political
interference, which is itself a political phenomenon.

This links the sub-field of central bank losses (including this paper),
to a broader literature on central bank independence (CBI) in the
discipline of comparative/international political economy. The political
economy approach to the topic differs from the purely economic accounts
in that the latter highlights the benefits of \emph{apolitical} central
banks in achieving sound economic outcomes such as stable inflation
(\citeproc{ref-Alesina2010}{Alesina \& Stella, 2010};
\citeproc{ref-Barro1983}{Barro \& Gordon, 1983};
\citeproc{ref-Kydland1977}{Kydland \& Prescott, 1977};
\citeproc{ref-Lohmann2008}{Lohmann, 2008};
\citeproc{ref-Rogoff1985}{Rogoff, 1985}), while the former explains the
delegation outcome as a result of political bargaining rather than the
promotion of the economic ideal (\citeproc{ref-Alesina1997}{Alesina,
1997}; \citeproc{ref-Bernhard1998}{Bernhard, 1998};
\citeproc{ref-Bernhard2002}{Bernhard et al., 2002};
\citeproc{ref-FernandezAlbertos2015}{Fernández-Albertos, 2015};
\citeproc{ref-Hallerberg2002}{Hallerberg, 2002};
\citeproc{ref-Lohmann1997}{Lohmann, 1997};
\citeproc{ref-Mukherjee2008}{Mukherjee \& Singer, 2008};
\citeproc{ref-Woodruff2019}{Woodruff, 2019}). This paper adopts the
political economy approach by assuming that indemnity decisions are
\emph{endogenous} to preferences of the government and central bank in
theoretical and empirical analyses.

This literature review reveals that, despite the current literature's
acknowledgement of central bank losses and their coverage as political
economy issues, there has not yet been a formal theoretical framework
that treats the indemnity agreement as an \emph{endogenous} decision to
the fiscal-monetary interaction or guides empirical effort on
quantitatively evaluating the causal impact of indemnity on central bank
financial strength. This paper aims to contribute to the literature by
providing such theoretical framework and empirical analysis. The
theoretical and empirical results can be used for the cost-benefit
analysis of the indemnity and future institutional designs, as sought by
the House of Commons Treasury Committee (\citeproc{ref-HCTC2024}{2024}).

\section{Theory}\label{sec-theory}

The section first lays out the \hyperref[model-setup]{Model Setup} of
the game theoretical model, then presents the key
\hyperref[sec-analytical-main]{analytical} and
\hyperref[sec-simulation]{Numerical Evaluation} results, omitting the
tedious \hyperref[sec-model-app]{mathematical analysis}.

\subsection{Model Setup}\label{model-setup}

Consider a two-period game (\(t\in\{1,2\})\) between a government \(G\)
and a central bank \(B\).

\textbf{Indemnity}. The concept of indemnity is central to this
theoretical model. In this model, the indemnity is denoted by \(x\) and
is an \emph{endogenous} decision by the government at the start of
period 1, which will be explained further. In either period
\(t\in\{1,2\}\), if profits are made \(p_t\geq0\), all profits are
transferred to the government. In case of losses \(p_t<0\), an
indemnified central bank (\(x=1\)) receives a payment of \(|p_t|\) from
the government to cover the losses. An non-indemnified central bank
(\(x=0\)) bears the losses itself. This setting is in line with the
real-world distribution arrangements where profits are mostly
transferred to the treasury (\citeproc{ref-Long2024}{Long \& Fisher,
2024}).

\textbf{Central Bank's (}\(B\)\textbf{) actions and preferences}.

In each period \(t\in\{1,2\}\), \(B\) chooses a level of monetary policy
\(i_t\) and a level of risk-taking \(r_t\geq0\). Its period utility
(\(U_{Bt}\)) is determined by the level of inflation (\(\pi_t\%\)) and
the size of losses when it is not indemnified. For simplicity it is
assumed that there is no discounting between the two period
(\(U_B=U_{B1}+U_{B2}\)). It is worth noting that the level of
risk-taking \(r_2\) can only be increased and not decreased in the
second period, reflecting the difficulty of active Quantitative
Tightening (QT) in the reality. Throughout this model, we assume that
\(B\) chooses the \emph{minimum} level of risk when it is indifferent to
eliminate multiple equilibria. The central bank's period utility
function is given by:

\[
U_{Bt} = -(\pi_t-2)^2 + \alpha(1-x_t)\min\{p_t,0\}
\]

The first term is the quadratic loss function of inflation. This follows
the inflation target of 2\% across the developed world. The second term
reflects the fear of losses for a \emph{non-indemnified} central bank.
As for a indemnified central bank (\(x=1\)), all profits and losses are
due to/from the government and the term is eliminated from the utility
function. As for a non-indemnified central bank, additional
\emph{profits} do not increase its utility since they are transferred to
the government \(G\) (\(\frac{\partial}{\partial p_t}U_{Bt}=0\) when
\(p_t\geq0\)). Nevertheless, additional \emph{losses} linearly reduce
its utility by \(\alpha\):

\[
\frac{\partial}{\partial p_t}U_{Bt}=\alpha~\text{when}~p_t<0
\]

\(\alpha\) denotes the central bank's sensitivity toward losses, it is
assumed that all central banks are more or less sensitive to losses
(\(\alpha>0\)), as argued by Goncharov et al.
(\citeproc{ref-Goncharov2023}{2023}) and Diessner
(\citeproc{ref-Diessner2023}{2023}). This sensitivity is also known to
the other player, the government \(G\).

\textbf{Government's (}\(G\)\textbf{) actions and preferences}. The
government chooses to indemnify the central bank (\(x=0\)) or not
(\(x=1\)) at the start of period 1. In both periods, the government
chooses level of fiscal surplus net of the transferred profit (\(f_t\))
simultaneously with the central bank's monetary policy decisions
(\(i_t\) and \(r_t\)). A higher \(f_t\) means higher fiscal surplus or
lower fiscal deficit in the period. \(F_t\) denotes the \emph{total}
budget surplus (deficit), including the profit remittance from the
central bank. The government's period utility function given by:

\begin{align*}
U_{Gt} &=C(F_t)+ g_t \\
&=C(\max\{p_t,p_tx\}+f_t)+ g_t \\
&=\begin{cases}
C(p_t+f_t)+g_t~\text{if } x=1 \\
C(\max\{p_t,0\}+f)+g_t~\text{if } x=0
\end{cases}
\end{align*}

\(C( F)\) is a function that represents the component of total fiscal
surplus/deficit in \(G\)'s utility. A greater fiscal surplus or a
smaller budget deficit increases \(G\)'s utility
(\(\frac{\partial}{\partial F}C(F)>0\)) at a decreasing rate
(\(\frac{\partial^2}{\partial F^2}C(F)<0\)). The justification for the
diminishing marginal utility of fiscal surplus is the increasing
marginal loss of popularity from higher taxes and lower public good
provision. This function is also known to the other player, the central
bank \(B\).

In case of indemnity (\(x=1\)), the first term collapses into
\(C(p_t+f_t)\), which implies that government bears the full benefits
(costs) of central bank profits (losses). In case of no indemnity
(\(x=0\)), the maximisation reduces to \(\max\{p,0\}\) so the government
only enjoys the profits and does not bear the losses.

The second term (\(g_t\)) is the real GDP growth of the period in
percentage points. The government prefers higher real GDP growth. Here a
linear function of growth is assumed for simplicity.

Hence, one can compare different government's sensitivity to overall
fiscal surplus (deficit) by comparing the level of \(F\) required to
achieve the same level of marginal utility, as in
Figure~\ref{fig-marginal-C}:

\begin{figure}

\centering{

\scalebox{1.25}{
\begin{tikzpicture}
\begin{axis}[
    axis lines = left,
    xlabel = \(F\),
    ylabel = {\(\frac{\partial C}{\partial F}\)},
]
%Below the red parabola is defined
\addplot [
    domain=0:2, 
    samples=100, 
    color=red,
]
{e^(-x+2)/2};
\addlegendentry{High}
%Here the blue parabola is defined
\addplot [
    domain=-1:2, 
    samples=100, 
    color=blue,
    ]
    {e^(-x+1)/2};
\addlegendentry{Low}

\addplot[mark=none, black, thick, dotted] coordinates {(-1,1) (1.3068,1)};
\addplot[mark=none, black, thick, dotted] coordinates {(1.3068,0) (1.3068,1)};
\addplot[mark=none, black, thick, dotted] coordinates {(0.3068,0) (0.3068,1)};

\end{axis}
\end{tikzpicture}
}

}

\caption{\label{fig-marginal-C}Illustration of the marginal utilities of
fiscal surplus/deficit with high/low fiscal conservatism}

\end{figure}%

It can be seen in Figure~\ref{fig-marginal-C} that a government with a
higher sensitivity to fiscal surplus/deficit requires a larger total
fiscal surplus (\(F\)) to achieve the same level of marginal utility as
a government with a lower sensitivity. Therefore, we can measure a
government's fiscal sensitivity by the level of fiscal surplus/deficit
required to achieve any arbitrary level of marginal utility. For
convenience of later analysis, we choose this level to be 1. Therefore,
we can denote the government's fiscal sensitivity by an exogenous
parameter \(\rho\) which measures fiscally conservatism:

\[
\rho=\left( \frac{\partial C}{\partial F} \right)^{-1}(1)
\]

\textbf{Simplified macro-economic setting}. In a simplified
macro-economic setting, the inflation (\(\pi_t\)) and real growth rate
(\(g_t\)) are both determined by the fiscal (\(f_t\)) and monetary
(\(i_t\)) policies, a demand shock (\(\epsilon_{dt}\)) and a supply-side
shock (\(\epsilon_{st}\)), where \(\epsilon_{st}<0\) denotes a negative
shock (e.g.~supply-chain interruption) that leads to lower growth and
higher inflation.

\begin{align*} g_t &= 4-f_t-i_t+\epsilon_{dt}+\epsilon_{st}\\ \pi_t &= 4-f_t-i_t+\epsilon_{dt}-\epsilon_{st} \end{align*}

We assume a common belief between the government and central bank that
the second period demand shock is drawn from a uniform distribution and
there will be no second period supply shock. The anticipation of no
supply shock echoes the rarity of such shocks in reality (1973 oil
crisis and 2021-23 global energy crisis). The uniform distribution for
the demand shock is chosen for its simplicity in the later analysis. The
support for the demand shock is set to be \([-2,2]\) to ensure that both
quantitative easing and monetary tightening are possibly needed
(although not necessarily implemented) in the second period - this
requires a support width of at least 2. An additional 2 units of support
width is added to expand the policy space and to avoid corner solutions.

\begin{align*}
\tilde\epsilon_{d2} &\sim U(-2, 2) \\
\tilde\epsilon_{s2}&=0 \\
\end{align*}

To reflect the zero lower bound of monetary policy and the necessity of
quantitative easing, the lower bound of monetary policy is determined by
\(r_t\):

\[
i_t\geq-r_t
\]

When no additional risk is taken by the central bank (\(r_t=0\)), the
monetary policy cannot go beyond zero (\(i_t\geq0\)). One can conceive
of the level of risk-taking \(r_t\) as reflecting the scale of QE and
the maturity of the bond assets purchased during QE. Larger scales of QE
and the longer maturity of the purchased bonds translate into higher
risks borne by \(B\).

The profit (\(p\)) is determined by monetary policy (\(i\)) and the
level of risk-taking (\(r\)):

\[
p_t =-\psi(i_t-2)r_t
\]

Here \(\psi>0\) denotes the sensitivity of profits to monetary policy
and risk-taking. A higher \(\psi\) implies higher losses/profits given
the same level of risk-taking and monetary policy. One can conceive of
\(i=2\) as the ``neutral'' interest rate at which no profits/losses are
made. Monetary policies above (below) this level lead to losses
(profits).

\textbf{Timing}. The sequence of the game is as follows:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The types of the central bank (\(\alpha\)) and the government
  (\(\rho\)) are exogenously determined and known to both players.
\item
  Global Financial Crisis occurs; first period shocks are revealed
  (\(\epsilon_{d1}=-1\), \(\epsilon_{s1}=0\)). The government decides
  whether to indemnify the central bank (\(x=1\)) or not (\(x=0\)).
\item
  The central bank chooses the level of monetary policy and risk-taking
  (\(i_1\) and \(r_1\)). Simultaneously, the government determines the
  level of fiscal policy (\(f_1\)).
\item
  First period payoffs are realized.
\item
  COVID-19 and the full-scale Russian invasion of Ukraine occur; second
  period shocks are revealed (\(\epsilon_{d2}=0\),
  \(\epsilon_{s2}=-2\)).
\item
  The central bank chooses the level of monetary policy and risk-taking
  (\(i_2\) and \(r_2\)). Simultaneously, the government determines the
  level of fiscal policy (\(f_2\)).
\item
  Second period payoffs are realized. Game ends.
\end{enumerate}

The solution concept is Subgame Perfect Nash Equilibrium (SPNE).

\subsection{Analytical Results}\label{sec-analytical-main}

The game is solved by backward induction. This section analyses the two
subgames with indemnity (\(x=1\)) and without indemnity (\(x=0\)). The
solution to the indemnity decision (\(x\)) is evaluated numerically in
Section~\ref{sec-indemnity}. Full model derivation and analysis are
available in Appendix \ref{sec-model-app}.

\subsubsection{\texorpdfstring{Subgame with Indemnity
(\(x=1\))}{Subgame with Indemnity (x=1)}}\label{subgame-with-indemnity-x1}

Complete analysis of this subgame is available in Appendix
\ref{sec-model-app-indem}. This section summarises the main findings of
the subgame equilibrium and explains the intuition.

As for the government \(G\), its first period fiscal policy \(f_1\) does
not affect the second period. Consequently, the government simply plays
a dominant strategy in each stage game which satisfies:

\[
f_t^*(x=1)=\rho-p_t
\]

This implies that the fiscal policy \(f_t\) is determined by the fiscal
sensitivity of government (\(\rho\)) and the profit (losses) transferred
from (to) the central bank \(B\). Additional profits received from \(B\)
are immediately spent by \(G\) and losses by \(B\) would incur a fiscal
contraction of the same size. This result is summarised by Proposition
\ref{prp-mondom} of \emph{monetary dominance}.

\begin{restatable}[Monetary Dominance]{prp}{mondom}
\label{prp-mondom}
Under fiscal indemnity for central bank losses, the fiscal policy of the government is constrained by the size of the profit (indemnity) payment from (to) the central bank.
\end{restatable}

The term ``monetary dominance'' is coined as a mirroring concept to
\emph{fiscal dominance}, which refers to the possibility that the
government's excessive fiscal deficits ``dominate'' central bank efforts
to keep inflation low (\citeproc{ref-Calomiris2023}{Calomiris, 2023}).
Nevertheless, monetary dominance defined in this paper departs from that
in the existing literature (\citeproc{ref-Barwell2016}{Barwell, 2016};
\citeproc{ref-Bonam2024}{Bonam et al., 2024};
\citeproc{ref-Hinterlang2022}{Hinterlang \& Hollmayr, 2022}) which
highlights the constraints of \emph{interest rates} on fiscal borrowing.
In contrast, this paper emphasizes the indemnity payments as a
\emph{forced expenditure} by the government.

As a result of the monetary dominance under the indemnity, the central
bank is able to achieve the inflation target (which is assumed to be 2\%
in the model) in both periods. This is known as Proposition
\ref{prp-stabinf}.

\begin{restatable}[Stable inflation under indemnity]{prp}{stabinf}
\label{prp-stabinf}
The inflation target can always be achieved when the central bank is indemnified by the government against losses.
$$
\pi_t(x=1)=2
$$
\end{restatable}

This confirms the mainstream economic literature's support of indemnity
for stable inflation.

\subsubsection{\texorpdfstring{Subgame without Indemnity
(\(x=0\))}{Subgame without Indemnity (x=0)}}\label{subgame-without-indemnity-x0}

Complete analysis of this subgame is available in Appendix
\ref{sec-model-app-noindem}. This section merely discusses the main
analytical findings of the subgame equilibrium.

Intuitively, a central bank without indemnity has to bear its own risks
and would not choose a higher risk level than in an indemnified
counterfactual scenario. This result is formally proven in Proposition
\ref{prp-prudence}.

\begin{restatable}[Central bank prudence without indemnity]{prp}{prudence}
\label{prp-prudence}
Indemnity against losses never reduces a central bank's risk level.
$$
r^*_t(x=0)\leq r^*_t(x=1)
$$
\end{restatable}

Proposition \ref{prp-prudence} can be understood as moral hazard, where
the risk of the central bank is \emph{completely} transferred to the
government under the indemnity agreement
(\citeproc{ref-Landes2013}{Landes, 2013}). It is therefore not
surprising to find central banks without indemnity tend to choose lower
risk-levels.

As a result of this \emph{prudence}, the central bank cannot choose
\(i\) low enough to boost inflation back to target (2\%) in period 1. As
a result. inflation is \emph{below} the target in period 1 under
deflationary pressure. It is worth noting that the \emph{deflationary
bias} increases with the extent of \emph{prudence}
(\(r^*_1(x=1)-r_1^*(x=0)\)), as stated in Proposition
\ref{prp-deflationary}.

\begin{restatable}[Deflationary bias without indemnity]{prp}{deflationary}
\label{prp-deflationary}
If the central bank chose a lower risk level due to no indemnity, there would be a deflationary bias negatively correlated with the chosen risk level in the aftermath of the GFC.
$$
\pi_1(x=0)-2=r_1^{2}(x=0)-r_1^{2}(x=1)+3r_1(x=0)-3r_1(x=1)\leq0
$$
\end{restatable}

Moreover, due to the fear of losses, the central bank hesitates to adopt
contractionary monetary policy (high \(i_2\)) in the second period that
is required to suppress inflation to the 2\% target in period 2. Notice
that this \emph{inflationary bias} increases with the chosen risk level
(\(r_1(x=0)\)) and central bank sensitivity (\(\alpha\)), as stated in
Proposition \ref{prp-inflationary}.

\begin{restatable}[Inflationary bias without indemnity]{prp}{inflationary}
\label{prp-inflationary}
If the central bank decided to implement QE ($r_1>0$) without indemnity ($x=0$),
there would be an inflationary bias under inflationary pressure. The extent of this bias is proportional to the first period risk level ($r_1$) and the central bank's financial sensitivity ($\alpha$)
$$
\max\tilde\pi_2-2=\frac{\alpha\psi r_1(x=0)}{2}
$$
\end{restatable}

As later shown in \hyperref[sec-simulation]{Numerical Evaluation}, the
deflationary and inflationary biases depend on the preferences of the
government and central bank (\(\rho\) and \(\alpha\)). This information
is useful for assessing the public finance-price stability trade-off in
future policy making, which will be discussed in
\hyperref[sec-conclusion]{Conclusion}.

\subsection{Numerical Evaluation}\label{sec-simulation}

Due to the piece-wise nature of the solution to risk-taking without
indemnity (\(r^*(x=0)\)), which can be seen in Figure~\ref{fig-r} and
Appendix \ref{sec-model-app-noindem}, full analytical solutions are
unnecessarily long and unintuitive to understand. Therefore, the SPNE
outcomes are numerically evaluated and visualised with different values
of \(\rho\) (government's fiscal conservatism) and \(\alpha\) (central
bank's loss sensitivity). As justified in Equation (\ref{eq-rho-range})
of Appendix \ref{sec-model-app-noindem}, \(\rho\) is set such that
\(\rho\in(1,2)\) to ensure both deflationary and inflationary pressures
were expected by the players in period 2. \(\psi\) (profit coefficient)
is set to 1 for convenience, other values of \(\psi\) show a similar
pattern. The range for \(\alpha\) is set to \(\alpha\in(0,4\sqrt3]\) to
ensure concavity of the utility function\footnote{It requires that
  \(\alpha\leq\frac{\sqrt{\frac{8(4\psi+2)}{2-\rho}}}{\psi}\leq\frac{\sqrt{\frac{8(4+2)}{2-\rho_{\min} }}}{1}=\sqrt{\frac{48}{1}}=4\sqrt3\)}.

\subsubsection{\texorpdfstring{Government's Indemnity Decision
(\(x\))}{Government's Indemnity Decision (x)}}\label{sec-indemnity}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-indemnity-1.pdf}}

}

\caption{\label{fig-indemnity}Indemnity decision with respect to
\(\rho\) and \(\alpha\)}

\end{figure}%

Figure~\ref{fig-indemnity} shows the indemnity outcome with respect to
the government's fiscal conservatism (\(\rho\)) and the central bank's
sensitivity to losses (\(\alpha\)). The blue area represents the values
of \(\rho\) and \(\alpha\) where the central bank is indemnified; no
indemnity is granted in the red and grey areas. The grey area denotes
values for which the central bank does not adopt contrationary monetary
policy even in cases of extreme inflationary pressure such as COVID-19
without indemnity, which are not representative of the control group in
our empirical analysis and are thus excluded to avoid confusion.

We define domain \(D\) to denote combinations of \(\alpha\) and \(\rho\)
in the blue or red areas that are relevant to our empirical analysis:

\[
D=\{(\alpha, \rho)|0<\alpha\leq4\sqrt{3},1<\rho<2,\alpha\leq\frac{4-2\rho}{r(x=1)}\}
\]

Figure~\ref{fig-indemnity} suggests that the indemnity decision (\(x\))
depends primarily on the government fiscal conservatism (\(\rho\)), and
to a lesser extent, the central bank's sensitivity to losses
(\(\alpha\)).

A fiscally liberal government (low \(\rho\)) is more likely to indemnify
the central bank (in blue area). When the government's sensitivity
(\(\rho\)) is low, inflationary pressure is more likely in the second
period and the central bank would only be willing to take zero or low
risk without indemnification. As such, the government expects to gain
more from indemnification because of higher benefits in the first period
and lower opportunity cost in the second period. In the first period,
the indemnification has a greater impact on QE for a fiscally liberal
government, which implies higher positive impact on first-period growth
rate. In the second period, the low risk level in the non-indemnified
counterfactual scenario means that even a non-indemnified central bank
would be more determined to suppress inflation and growth in an
inflationary scenario, just as an indemnified central bank would. This
implies that the opportunity cost of indemnification is lower for a
fiscally liberal government.

On the other hand, the impact of the central bank's sensitivity to
losses (\(\alpha\)) on the indemnity decision is less pronounced.
Counter-intuitively, a less sensitive bank (low \(\alpha\)) is more
likely to receive indemnity, although a highly sensitive bank may also
be indemnified. This seemingly paradoxical result arises from the
government's forward-looking assessment of period 2 opportunity costs.

When \(\alpha\) is low, the central bank cares less about financial
losses. Consequently, even without indemnification, a low-\(\alpha\)
bank would still implement tight contractionary monetary policy in
period 2 to suppress inflation, despite the financial losses this
entails. Since the non-indemnified bank's period 2 behaviour closely
resembles that of an indemnified bank, the government faces a lower
opportunity cost from granting indemnity---the government would face
similar period 2 outcomes either way. This reduction in opportunity cost
makes indemnification more attractive to the government when \(\alpha\)
is low\footnote{Mathematically, as \(\alpha\to0\), the loss-aversion
  term in the central bank's utility function
  \(U_{Bt} = -(\pi_t-2)^2 + \alpha(1-x_t)\min\{p_t,0\}\) vanishes,
  making the non-indemnified bank's optimization problem converge to
  that of an indemnified bank. Here, \(\pi_t\) is the inflation rate and
  \(p_t\) is the central bank profit. This convergence implies that
  period 2 outcomes become similar regardless of indemnity status,
  reducing the government's opportunity cost of indemnification.}.

Nevertheless, part of this effect is offset by first-period
considerations. A less sensitive non-indemnified central bank is almost
as willing to take high risks in period 1 as an indemnified bank would,
which implies that the government's benefits from indemnification are
lower in the first period. The net effect still favours indemnification
for low \(\alpha\), but the magnitude is dampened by this offsetting
mechanism.

Nevertheless, it will be shown in the Section~\ref{sec-discussion} that
the UK is likely a combination of relative fiscal liberalism (low
\(\rho\)) and high central bank financial sensitivity (\(\alpha\)), due
to the lack of independence of the BoE.

\subsubsection{\texorpdfstring{Central Bank's Optimal Risk Levels
(\(r^*\))}{Central Bank's Optimal Risk Levels (r\^{}*)}}\label{sec-optimal-r}

In our setting, an inflationary shock is realised in period 2; the
second-period risk levels are kept constant. Therefore, we only need one
plot for \(r^*=r^*_1=r^*_2\).

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-r-1.pdf}}

}

\caption{\label{fig-r}Central bank's optimal risk levels (\(r^*\)) with
respect to \(\rho\) and \(\alpha\)}

\end{figure}%

As shown in Figure~\ref{fig-r}, when the bank is indemnified (\(x=1\)),
the chosen risk level (\(r^*\)) increases with the government's fiscal
conservatism (\(\rho\)). This is because when the government is more
fiscally conservative, more expansionary monetary policy is needed to
stimulate the economy, hence higher risks needed.

On the other hand, when the central bank is not indemnified (\(x=0\)),
the risk level chosen by the central bank (\(r^*\)) is irregular. When
the government's fiscal conservatism (\(\rho\)) is low but the bank's
sensitivity to losses (\(\alpha\)) is high, the central bank is
reluctant to take any risks (denoted by the dark blue area) due to the
bank's risk aversion and second-period inflationary pressure resulting
from the government's fiscal liberalism. Note that when the bank is more
risk-averse (higher \(\alpha\)), the government needs to be more
fiscally conservative (higher \(\rho\)) for the bank to trigger QE
(adopt a positive \(r\)) without indemnity. This is referred to as
Proposition \ref{prp-reluctance}. Proposition \ref{prp-reluctance}
provides basis for Proposition \ref{prp-belt}.

\begin{restatable}[Reluctance to QE driven by central bank loss sensitivity]{prp}{reluctance}
\label{prp-reluctance}
Without indemnity ($x=0$), the central bank $B$ is reluctant to engage in QE ($r=0$) unless the government's fiscal conservatism ($\rho$) is sufficiently high. This reluctance increases with the central bank's sensitivity to losses ($\alpha$), i.e. the level of $\rho$ needed to trigger QE without indemnity increases with $\alpha$.
\end{restatable}

We then explore the effect of the indemnity (\(x\)) on risk taking
(\(r^*\)) by subtracting the untreated from the treated potential
outcomes, as in Figure~\ref{fig-effect-r}.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-effect-r-1.pdf}}

}

\caption{\label{fig-effect-r}Predicted effects of the indemnity on risk
taking (\(r\)) with respect to \(\rho\) and \(\alpha\)}

\end{figure}%

The results show that, for the domain of \(\alpha\) and \(\rho\) in this
numerical evaluation (\(D\)), the indemnity strictly increases
risk-taking (i.e.~positive effect of indemnity on the scale/depth of
QE):

\[
r^*(x=0,\alpha,\rho)<r^*(x=1,\alpha,\rho)~\forall(\alpha,\rho)\in D
\]

Moreover, note that the positive effect is strongest when \(\alpha\) is
proportional to \(\rho\), shown as a ``belt'' in light blue in
Figure~\ref{fig-effect-r}. This corresponds to the \emph{boundary} of
the area of parameters where the central bank would not engage in QE
without indemnity (\(r^*(x=0)=0\)), which has been discussed in
Proposition \ref{prp-reluctance}. Note that within the belt, the effect
is highest when \(\alpha\) is high. This is because a high \(\alpha\)
requires a sufficiently high \(\rho\) to trigger QE without indemnity
(Proposition \ref{prp-reluctance}). A relatively high \(\rho\) implies
the government is reluctant to stimulate the economy with fiscal policy
and more QE (\(r\)) is needed to restore growth and inflation in period
1. When indemnified (\(x=1\)), the bank \(B\) would be willing to take
such high risks (\(r\)); nevertheless, no risk would be taken at all
without indemnity (\(r^*(x=0)=0\)). Hence the highest effect of the
indemnity on risk-levels when both \(\alpha\) and \(\rho\) are high on
the ``belt''.

The ``belt'' pattern of the effect of indemnity drives similar patterns
for below-target inflation in period 1 (see Figure~\ref{fig-pi1}), and
the effect of indemnity on central bank profits (see Proposition
\ref{prp-belt}).

\subsubsection{Period 1 - Deflationary Episode Following
GFC}\label{sec-sim-def}

We first examine the potential outcomes in period 1, which features the
deflationary pressure following the GFC. We first look at the growth and
inflation rates which are identical in the first period.
Figure~\ref{fig-pi1} shows that indemnity stabilises the
growth/inflation rates at 2\% in the first period (as predicted by
Proposition \ref{prp-stabinf}), whereas growth and inflation can be
lower in the non-indemnified scenario. Note that in the non-indemnified
scenario, the 2\% inflation target is sometimes \emph{almost} achieved,
especially for countries which do not self-select into indemnity. This
implies that naive comparisons of inflation outcomes are likely not
informative. The results confirm our conclusion in
Section~\ref{sec-indemnity} that the gain from indemnity in the first
period growth rate is higher for a \emph{relatively} low-sensitivity
(\(\rho\)) government with a highly sensitive (\(\alpha\)) central bank.
The pattern where the inflation target is severely under-achieved (in
dark blue) again resembles the ``belt'' in Figure~\ref{fig-effect-r} and
Figure~\ref{fig-belt}. It will be shown that the UK is located on the
belt.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-pi1-1.pdf}}

}

\caption{\label{fig-pi1}First period growth and inflation rates
(\(g_1=\pi_1\)) with respect to \(\rho\) and \(\alpha\)}

\end{figure}%

As for the potential outcomes of central bank profit in period 1
(\(p_1\)), results in Figure~\ref{fig-p1} looks highly similar to
risk-taking (\(r^*\)) results in Figure~\ref{fig-r}. This should not be
surprising as in period 1, the interest rates are determined by the risk
levels (\(i^*_1=-r^*_1\)) as in Figure~\ref{fig-i1}. Therefore, the
first period profits are a function of risk levels only. Because of the
greater risks taken under indemnity, the indemnity is expected to have a
\emph{positive} impact on the central bank profits. It will be shown in
Section~\ref{sec-belt} that the effect is most prominent on the same
``belt'' as in Figure~\ref{fig-effect-r}.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-p1-1.pdf}}

}

\caption{\label{fig-p1}First period central bank profit (\(p_1\)) with
respect to \(\rho\) and \(\alpha\)}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-i1-1.pdf}}

}

\caption{\label{fig-i1}First period monetary policy (\(i_1\)) with
respect to \(\rho\) and \(\alpha\)}

\end{figure}%

\subsubsection{Period 2 - Inflationary Crisis of
COVID-19}\label{sec-sim-inf}

We model the impact of COVID-19 (and the contemporaneous full scale
Russian invasion of Ukraine) as an unexpected negative supply shock
(\(\epsilon_{d2}=0\), \(\epsilon_{s2}=-2\)) that is outside the
government and central bank's belief (\(\tilde\epsilon_{s2}=0\)).

The potential outcomes of monetary policy (\(i_2\)) are presented in
Figure~\ref{fig-i2}. Results show that the interest rates with indemnity
(\(x=1\)) tend to be lower than those without indemnity (\(x=0\)) when
either \(\rho\) or \(\alpha\) is low, and higher otherwise.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-i2-1.pdf}}

}

\caption{\label{fig-i2}Second period monetary policy (\(i_2\)) with
respect to \(\rho\) and \(\alpha\)}

\end{figure}%

The results on inflation and growth outcomes in period 2 are more
important, because a key argument for central bank independence and
indemnity is the central bank's ability to suppress inflation against
the government's preference for growth. Results in Figure~\ref{fig-pi2}
confirms our proposition \ref{prp-stabinf} that the inflation target is
always achieved under indemnity.

Interestingly, the beneficial impact of indemnity on price stability is
only substantial for countries with high \(\rho\) and \(\alpha\), which
\emph{do not} self-select into the indemnity treatment. This is because
the central banks which received indemnity would have taken no/low risks
in a non-indemnified counterfactual and therefore not be constrained to
tackle inflation in the second period. This means naive comparisons of
inflation outcomes in countries with and without indemnity
\emph{overestimate} the importance of indemnity on stable price levels.
On the contrary, the trade-off between inflation and public finance
should be rethinked.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-pi2-1.pdf}}

}

\caption{\label{fig-pi2}Second period inflation and growth
(\(\pi_2=g_2+2\)) with respect to \(\rho\) and \(\alpha\)}

\end{figure}%

We finally look at the results for second-period profits (\(p_2\)) in
Figure~\ref{fig-p2}, which is the main hypothesis tested in the
empirical section. Counterintuitively, central banks which receive
indemnity \emph{do not necessarily} make higher losses compared with a
non-indemnified counterfactual. This observation is presented in a
clearer way in Figure~\ref{fig-p2-comp}. It can be seen that the
indemnity may \emph{save} losses when \(\alpha\) is low but increase
losses when \(\alpha\) is moderate or high. This is because when
\(\alpha\) is low, a non-indemnified bank is also determined to keep
inflation in control despite losses, and adopts much tighter monetary
policy in the inflationary episode to account for the unconstrained
fiscal policy. This combination of high risk and high interest rate
means the losses in the non-indeminified case are even higher than the
indemnified case. This is at odds with the conventional idea of moral
hazard.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-p2-1.pdf}}

}

\caption{\label{fig-p2}Central bank profit (\(p_2\)) with respect to
\(\rho\) and \(\alpha\)}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-p2-comp-1.pdf}}

}

\caption{\label{fig-p2-comp}Central bank profit comparison (\(p\)) with
respect to \(\rho\) and \(\alpha\)}

\end{figure}%

\subsubsection{Belt of Effect}\label{sec-belt}

In Figure~\ref{fig-p1} and Figure~\ref{fig-p2}, the numerical
evaluations of the potential outcomes of profits under the treatment
(indemnity) and control conditions are presented. By subtracting the
untreated from the treated outcomes, we can calculate the predicted
treatment effects, which are presented in Figure~\ref{fig-belt}.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-belt-1.pdf}}

}

\caption{\label{fig-belt}Predicted effects of indemnity on profits with
respect to \(\rho\) and \(\alpha\)}

\end{figure}%

The indemnity's effects are largest (denoted by dark blue/red) along a
``belt'' where \(\alpha\) is proportional to \(\rho\), where \(\rho\) is
moderately low. Although for period 2, the effect is also strong when
both \(\alpha\) and \(\rho\) are high (top right), this is ignored by
this paper as countries in this area do not self-select into treatment
and the empirical section focuses on the treatment effect \emph{on the
treated} (UK) only.

The ``belt'' patterns are similar to and driven by the ``belt'' of
effect of the indemnity on risk levels in Figure~\ref{fig-effect-r},
which is in turn driven by Proposition \ref{prp-reluctance}. The
intuition is that, along this belt, the central bank (\(B\)) would not
engage in QE (\(r^*(x=0)=0\)) at all without indemnity and therefore
would not generate any abnormal profits/losses in both periods
(\(p_t(x=0)=0\)). Nevertheless, along the belt the government is
sufficiently averse to fiscal deficit (\(\rho\) is sufficiently high)
such that the bank (\(B\)) would bear high risks in QE under indemnity
to stimulate growth and inflation in period 1 (relatively high \(r\)),
which results in profits and losses in periods 1 and 2, respectively.
The stark difference in the potential outcomes implies strong effects of
the indemnity:

\begin{restatable}[Belt of effect]{prp}{belt}
\label{prp-belt}
The effect of the indemnity on profits are strongest in size along a belt where $\alpha$ is proportiontal to $\rho$ for countries which self-select into indemnity. Along the belt, the effects are stronger when both $\alpha$ and $\rho$ are high.
\end{restatable}

In the \hyperref[sec-discussion]{Discussion} section we will try to
locate the UK on this belt of effect.

\subsection{Testable Hypotheses}\label{testable-hypotheses}

While the theoretical model sheds light on the effects of indemnity on
economic outcomes, and describes \hyperref[sec-indemnity]{conditions}
under which a government indemnifies its central bank, it crucially
refines the hypothesis to be tested. The main empirical hypothesis is:

\begin{restatable}[$H_{1}$]{hyp}{hypmain}
\label{hyp-main}
The UK Treasury's indemnity against QE losses has affected the BoE profitability.
\end{restatable}

Nevertheless, the \hyperref[sec-simulation]{theoretical model} reveals
that the direction of the impact depends on the demand and supply shocks
at the time. Under the deflationary shock after of the GFC, which
corresponds to \hyperref[sec-sim-def]{period 1} of the theoretical
model, the indemnity is expected to have \emph{increased} the central
bank profits. However, under the inflationary shocks since 2022, which
corresponds to \hyperref[sec-sim-inf]{period 2} of the theoretical
model, the impact of the indemnity on profitability can be
\emph{positive or negative} depending on the value of \(\alpha\). When
\(\alpha\) is moderate or high, the indemnity is expected to have
increased the losses, hence a \emph{negative} impact. This implies that
the impacts in the two periods can be in \emph{opposite} directions and
thus \emph{offsetting} each other if estimated in a combined analysis.
It is therefore more appropriate to break the main hypothesis into two
sub-hypotheses:

\begin{restatable}[$H_{1a}$]{subhyp}{hypdef}
\label{hyp-def}
The UK Treasury's indemnity against QE losses increased the BoE profits in the deflationary environment following GFC.
$$p_1^{UK}(x=1)-p_1^{UK}(x=0)>0$$
\end{restatable}
\begin{restatable}[$H_{1b}$]{subhyp}{hypinf}
\label{hyp-inf}
The UK Treasury's indemnity against QE losses has affected the BoE losses in the inflationary environment since 2022.
$$p_2^{UK}(x=1)-p_2^{UK}(x=0)\neq0$$
\end{restatable}

\section{Data}\label{sec-data}

For empirical analysis, panel data on 24 countries across 25 years
(1999-2023) are used. There are missing data for some countries,
resulting in 586 observations available. Countries are selected into the
sample if they 1) are members of the OECD or EU as proxies for advanced
economies and 2) introduced QE soon after the 2007-2008 GFC to exclude
countries which never introduced QE or introduced QE after COVID-19,
which are not comparable to the UK. More information on sample selection
and justification is provided in Appendix \ref{sec-sample}. 1999 is
chosen as the start date because the euro (€) was introduced in that
year, which constituted a major monetary change. The data availability
information is summarised in Figure~\ref{fig-panel}. Treatment is
assigned to the UK from 2009 onward, when the Asset Purchase Faciliy
(APF) was created under the UK Treasury's indemnity.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-panel-1.pdf}}

}

\caption{\label{fig-panel}Overview of the panel data availability}

\end{figure}%

\subsection{Dependent Variable}\label{dependent-variable}

The dependent variable of the main analysis is \emph{central bank profit
as a percentage of GDP}:

\[
Y_{it}=\frac{\text{Profit}_{it}}{\text{GDP}_{it}}\times 100\%
\]

The central bank profit data (\(\text{profit}_{it}\)) are mainly sourced
from S\&P Capital IQ Pro (\citeproc{ref-SCIP2024}{2024}) as ``Net Income
Before Taxes'', where data for most central banks in the sample are
available from 2010 onward\footnote{For consistency, the SNP Financial
  source is used within the S\&P Capital IQ Pro dataset.}. They are
supplemented by data hand-collected from central bank websites, using
the same calculation as S\&P Capital IQ Pro
(\citeproc{ref-SCIP2024}{2024}). A complete list of financial statement
sources for hand-collected data are given in Appendix \ref{sec-source}.
For the UK, the net cash transfers from the BoE APF to HM
Treasury\footnote{From 2010 to 2012, no transfers were made and the
  profits accumulated until the 2013 transfer. To reflect the true
  profitability, the net interest receivable is used for 2010-12 and
  their sum is deducted from the 2013 transfer.} are added to the BoE
net income to make the profit accounts comparable. This is because, any
profits made from QE by the APF are transferred to the Treasury and not
recorded as profits of the BoE or APF.
Table~\ref{tbl-profit-illustration} provides an example of such
calculation for 2014 and 2023 and reveals that the indemnity transfers
are very large relative to the reported profits of the BoE. The data for
UK indemnity cash transfers can be found from the Office for National
Statistics (\citeproc{ref-ONS2024}{2024})\footnote{See Worksheet PSA9B
  of the ONS dataset.}.

\begin{longtable}[]{@{}lccr@{}}
\caption{Example of BoE Profit calculation
(£mn)}\label{tbl-profit-illustration}\tabularnewline
\toprule\noalign{}
Year & Indemnity Transfer & Net Income & Total Profit \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Year & Indemnity Transfer & Net Income & Total Profit \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2014 & 10,898 & 198 & 11,096 \\
2023 & -37,378 & 33 & -37,345 \\
\end{longtable}

The GDP data (\(\text{GDP}_{it}\)) are provided by the World Bank Open
Data (\citeproc{ref-WBOD2024}{2024}). For most countries, the current
GDP in the local currency (LCU) is used. For countries which changed
their currency (to the euro) during the time span, GDP (current US\$) is
used and converted to their local currency using the year-average
official exchange rate, which is also sourced from World Bank Open Data
(\citeproc{ref-WBOD2024}{2024}).

In the \hyperref[sec-bias]{supplementary analysis}, the policy interest
rates and central bank liabilities (as a percentage of GDP) are used as
dependent variables. The policy interest rate data are primarily from
FRED (\citeproc{ref-FRED2024}{2024})\footnote{Under the name of
  ``Immediate Rates (\textless24 hours)''. The only exception is the UK
  policy rates, which are directly sourced from the
  \href{https://www.bankofengland.co.uk/-/media/boe/files/monetary-policy/baserate.xls}{BoE
  website}.}. Data on central bank liabilities are obtained from same
sources as profit, primarily from S\&P Capital IQ Pro
(\citeproc{ref-SCIP2024}{2024}).

\subsection{Covariates}\label{covariates}

Inspired by Goncharov et al. (\citeproc{ref-Goncharov2023}{2023}), the
empirical analysis includes as covariates central bank governor
reappointability and whether the central bank is publicly traded,
because they may impact central bank financial results and the
self-selection into indemnity. Reappointability data are borrowed from
Goncharov et al. (\citeproc{ref-Goncharov2023}{2023}); the binary
variable is coded to 1 if at least one central bank governor served more
than one legal term during the sample period in the Dreher et al.
(\citeproc{ref-Dreher2008}{2008}) dataset. Three central banks in the
dataset (Japan, Belgium and Greece) are publicly traded and they are
coded as 1 in this variable. In addition, we control for the Euro Area
membership to account for the effect of the monetary union.

Commonly used macroeconomic indicators such as unemployment, growth and
inflation are \emph{intentionally excluded} as covariates because they
are endogenously affected by the treatment (indemnity).

Summary statistics of the variables in the dataset are shown in
Table~\ref{tbl-summary}.

\begin{table}[h]

\caption{\label{tbl-summary}Summary statistics of the data}

\centering{

\centering
\resizebox{\ifdim\width>\linewidth 1\linewidth\else\width\fi}{!}{
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]Q[]Q[]Q[]Q[]},
hline{2}={1-9}{solid, black, 0.05em},
hline{1}={1-9}{solid, black, 0.1em},
hline{8}={1-9}{solid, black, 0.1em},
column{1}={}{halign=l},
column{2-9}={}{halign=r},
}                     %% tabularray inner close
& Mean & SD & Min & Q1 & Median & Q3 & Max & N \\
Profit (\% of GDP) & \num{0.18} & \num{0.42} & \num{-2.15} & \num{0.04} & \num{0.14} & \num{0.29} & \num{3.35} & 579 \\
Liabilities (\% of GDP) & \num{43.72} & \num{55.58} & \num{0.92} & \num{16.95} & \num{28.66} & \num{51.62} & \num{509.86} & 580 \\
Interest rate & \num{1.17} & \num{1.74} & \num{-0.50} & \num{0.00} & \num{0.50} & \num{2.21} & \num{12.78} & 414 \\
Publicly traded & \num{0.13} & \num{0.33} & \num{0.00} & \num{0.00} & \num{0.00} & \num{0.00} & \num{1.00} & 586 \\
Euro Area & \num{0.65} & \num{0.48} & \num{0.00} & \num{0.00} & \num{1.00} & \num{1.00} & \num{1.00} & 586 \\
Governor reappointability & \num{0.48} & \num{0.50} & \num{0.00} & \num{0.00} & \num{0.00} & \num{1.00} & \num{1.00} & 586 \\
\end{tblr}
}

}

\end{table}%

\section{Empirical Strategy}\label{sec-empirical}

This paper uses the Dynamic Multilevel Latent Factor Model (DM-LFM)
proposed by Pang et al. (\citeproc{ref-Pang2021}{2021}) as the main
estimator for the empirical analysis. The DM-LFM is described as a
``Bayesian Alternative to Synthetic Control'' by the inventors and is
applicable to scenarios where the Difference-in-Differences (DID) and
Synthetic Control (SCM) estimators are applied, namely the estimation of
\emph{binary} treatment effects with Time-Series Cross-Sectional (TSCS)
data. Since in our case, the indemnity is a binary treatment and
country-year panel data are used, the DM-LFM estimator perfectly suits
our empirical purpose.

Similar to a growing family of SCM-like estimators for comparative case
studies, the DM-LFM estimates the causal impact by first predicting the
\emph{treated counterfactuals} (\citeproc{ref-Pang2021}{Pang et al.,
2021, p. 269}) and then calculating the \emph{difference} between the
observed outcomes and predicted counterfactuals as the estimate for the
Average Treatment Effect on the Treated (ATT). The basic idea behind the
DM-LFM is to ``perform a low-rank approximation of the observed
untreated outcome matrix so as to predict treated counterfactuals in the
(\(T\times N\)) rectangular outcome matrix.'' (p.270) This can be seen
in the functional form for \emph{untreated potential outcomes}, which is
given by:

\[
Y_{it}(c)=\mathbf{X}'_{it}\beta_{it}+\gamma_{i}'\mathbf{f}_t+\epsilon_{it}
\]

Where \(\mathbf{X}_{it}\) is a matrix of observed covariates and
\(\beta_{it}\) are their effects that can be \emph{heterogeneous across
units and over time}. \(\mathbf{f}_t\) is vector of \emph{latent
factors} which commonly affect all units, but their effects are allowed
to be \emph{heterogeneous across units} as suggested by the subscript
\(i\) of their coefficients \(\gamma_i\). This \emph{latent factor term}
(\(\gamma_{i}'\mathbf{f}_t\)) correct for biases arising from the
``potential correlation between the timing of the treatment and the
time-varying latent variables.'' (p.271) Bayesian stochastic model
searching is performed to search and estimate the parameters via an MCMC
algorithm\footnote{MCMC diagnostics are provided in Appendix
  \ref{sec-mcmc-diag}.}. As a result, the empirical \emph{posterior
distribution} of the treated counterfactuals and ATT estimates are
formed, with \emph{95\% credible intervals} given for inference.

The DM-LFM is particularly more suited for this paper compared to
traditional estimators such as DID and SCM: There is only one treated
unit (UK) and none of the existing standard errors produces valid
inference in this case for the Two-way Fixed Effects (TWFE)
difference-in-differences (DID) design (\citeproc{ref-Conley2011}{Conley
\& Taber, 2011}; \citeproc{ref-MacKinnon2023}{MacKinnon et al., 2023a},
\citeproc{ref-MacKinnon2023a}{2023b};
\citeproc{ref-MacKinnon2016}{MacKinnon \& Webb, 2016},
\citeproc{ref-MacKinnon2018}{2018}). The SCM relies on placebo
permutation tests for inference (\citeproc{ref-Abadie2021}{Abadie,
2021}) which cannot quantify uncertainty in traditional ways (as
confidence intervals) (\citeproc{ref-Pang2021}{Pang et al., 2021}). This
is in contrast to the DM-LFM, which is tailor-made for single (and few)
treated unit(s) and provides built-in uncertainty measures (credibility
intervals) that are easy to interpret.

The key assumption of the DM-LFM is \emph{latent ignorability}
(\citeproc{ref-Pang2021}{Pang et al., 2021, p. 274}):

\begin{restatable}[Latent ignorability]{asp}{latign}
\label{asp-latign}
Conditional on the observed pre-treatment covariates $\mathbf{X}_{i}$ and latent variables $\mathbf{U}_i$ (approximated by $\mathbf{f}_t$ and $\gamma_i$), the assignment mechanism is independent from the untreated potential outcomes for each unit $i$.
\end{restatable}

This is a \emph{relaxed} version of the parallel-trends assumption in
the conventional DID design. The difference is that, the TWFE-DID design
assumes a unit-specific \emph{constant} \(\mathbf{U}_i\) while the
DM-LFM also allows for heterogeneous treatment effects of common
time-varying factors. Similar to the parallel-trends, this assumption
\emph{cannot be tested directly}, but a placebo test of pre-trends can
serve as diagnostics. The results for the placebo test of pre-trends are
provided in Appendix \ref{sec-pretrend}. Moreover, one may legitimately
critique that information about central banks' loss sensitivity
(\(\alpha\)) cannot be extracted from pre-treatment outcomes, which may
constitute a threat to internal validity. Section~\ref{sec-bias} shows
that, by indirect tests guided by \hyperref[sec-theory]{Theory}, this
bias is \emph{downward} (i.e making our empirical results more
conservative).

Another assumption of the DM-LFM that is potentially violated is no
anticipation (\citeproc{ref-Pang2021}{Pang et al., 2021, p. 273}):

\begin{restatable}[No anticipation]{asp}{noant}
\label{asp-noant}
The current untreated potential outcome does not depend on whether the unit gets the treatment in the future.
\end{restatable}

As early as 2004, the then governor of BoE Mervyn King and Monetary
Policy Committee member Paul Tucker emphasised in public that effective
monetary policy might require further cooperation with the Treasury, in
an attempt to hint at the potential need for indemnity
(\citeproc{ref-Diessner2023}{Diessner, 2023}). If the BoE anticipated
that it would later receive indemnity and adjusted its behaviour
accordingly, Assumption \ref{asp-noant} would be violated. To address
this concern, an \hyperref[sec-main-early]{early treatment of 2004} is
adopted as a robustness check to the results with treatment in 2009.

\section{Results}\label{sec-results}

Recall that our main hypothesis (Hypothesis \ref{hyp-main}) is broken
into two sub-hypotheses:

\hypdef* 
\hypinf*

It is therefore necessary to divide the post-treatment period
(2009-2023) into a deflationary period (2009-2021) and an inflationary
period (2022-2023) and estimate the ATT in these periods separately.
Thanks to the DM-LFM, this can be achieved by averaging the posterior
distributions across years. The DM-LFM estimation results without
covariates are presented in Columns (1) and (3) in Table~\ref{tbl-main}
for the deflationary and inflationary periods, respectively; the
corresponding ATT estimates are visualised as red bars in
Figure~\ref{fig-effect}. Those with covariates are presented in Columns
(2) and (4) in Table~\ref{tbl-main} and the ATT estimates are visualised
as blue bars in Figure~\ref{fig-effect}. Note that the DM-LFM assumes
that the covariates' effects vary over time. Therefore, covariate
coefficients in (2) and (4) are different, albeit from the same
estimation.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-effect-1.pdf}}

}

\caption{\label{fig-effect}Estimated ATT of indemnity on BoE profits (\%
of UK GDP)}

\end{figure}%

\begin{table}[H]

\caption{\label{tbl-main}Main DM-LFM analysis results table for impact
of indemnity on BoE profits}

\centering{

\centering
\resizebox{\ifdim\width>\linewidth 1\linewidth\else\width\fi}{!}{
\begin{talltblr}[         %% tabularray outer open
entry=none,label=none,
note{}={+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001},
note{ }={95\% equal-tailed Credible Intervals in square brackets.},
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]},
hline{2}={5}{solid, black, 0.05em},
hline{3}={1-5}{solid, black, 0.05em},
hline{11}={1-5}{solid, black, 0.05em},
hline{2}={2,4}{solid, black, 0.05em, l=-0.5},
hline{2}={3}{solid, black, 0.05em, r=-0.5},
hline{1}={1-5}{solid, black, 0.1em},
hline{14}={1-5}{solid, black, 0.1em},
column{3,5}={}{halign=c},
cell{1}{1}={}{halign=c},
cell{1}{2}={c=2}{halign=c},
cell{1}{4}={c=2}{halign=c},
cell{2-13}{1}={}{halign=l},
cell{2-13}{2}={}{halign=c},
cell{2-13}{4}={}{halign=c},
}                     %% tabularray inner close
& Deflationary (2009-2021) &  & Inflationary (2022-2023) &  \\
& (1) & (2) & (3) & (4) \\
ATT & \num{0.395}** & \num{0.392}** & \num{-0.698}* & \num{-0.708}* \\
& [\num{0.122}, \num{0.676}] & [\num{0.107}, \num{0.679}] & [\num{-1.255}, \num{-0.161}] & [\num{-1.238}, \num{-0.185}] \\
Publicly traded &  & \num{0.001} &  & \num{-0.003} \\
&  & [\num{-0.006}, \num{0.010}] &  & [\num{-0.031}, \num{0.013}] \\
Euro Area &  & \num{0.000} &  & \num{-0.003} \\
&  & [\num{-0.007}, \num{0.009}] &  & [\num{-0.024}, \num{0.013}] \\
Reappointability &  & \num{0.000} &  & \num{-0.000} \\
&  & [\num{-0.004}, \num{0.005}] &  & [\num{-0.012}, \num{0.009}] \\
Observations & \num{586} & \num{586} & \num{586} & \num{586} \\
Treated Units & \num{1} & \num{1} & \num{1} & \num{1} \\
Control Units & \num{23} & \num{23} & \num{23} & \num{23} \\
\end{talltblr}
}

}

\end{table}%

Figure~\ref{fig-effect} and Table~\ref{tbl-main} show that the
covariates do not substantively change the results. The indemnity is
estimated to have increased BoE profits in the deflationary period
(2009-2021) by 0.39\% of the UK GDP and decreased them in the
inflationary period (2022-2023) by 0.7\% of the UK GDP, on average. The
effects are statistically significant at the 1\% and 5\% significance
levels, respectively.

Such effects are also \emph{substantively} significant in context: In
the 2014 budget, corporation tax accounted for 2.44\% of UK GDP
(\citeproc{ref-HMTreasury2014}{HM Treasury, 2014}), this means extra
revenue of 0.39\% of GDP arising from the indemnity in the deflationary
period would have substituted 16\% of corporation tax of the year. The
extra loss arising from the indemnity in the inflationary period is even
more prominent: the average loss of 0.7\% of GDP is approximately twice
as large as the extra revenue gain in the deflationary period.

The results are even more alarming if one zooms into specific years such
as 2023. Figure~\ref{fig-trend} gives the most intuitive overview of the
results by visually comparing the actual trend of BoE profits as a
percentage of GDP and the counterfactual path predicted by the DM-LFM
estimator with covariates. The solid and dashed lines represent the
treatment (indemnity agreement in 2009) and the inflationary shock
(2022), respectively. The shaded area denotes the 95\% credible interval
which can be used for inference at the 5\% significance level. It can be
seen that the BoE profits were \emph{substantively} \emph{lower in 2023}
than the estimated untreated counterfactual. In fact, in 2023 the extra
loss from the indemnity amounted to 1.5\% of GDP (\(p<0.01\)). This is
comparable to the size of the unfunded tax cuts (£45 billion) announced
in the controversial mini-budget of September 2022, which was 1.8\% of
the 2022 GDP (\citeproc{ref-BBC2022}{BBC, 2022}).

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-trend-1.pdf}}

}

\caption{\label{fig-trend}Estimated counterfactual and actual trends of
BoE profits as \% of UK GDP}

\end{figure}%

The empirical evidence above is sufficient to support Hypotheses
\ref{hyp-def} and \ref{hyp-inf} that the indemnity significantly
increased the BoE profits in the deflationary period, and affected them
in the inflationary period. Furthermore, evidence indicates that the
impact in the inflationary period is \emph{negative}, i.e., the
indemnity incurred extra losses to the BoE during monetary tightening.

\section{Robustness Checks}\label{sec-robustness}

Besides the placebo tests of pre-trends in Appendix \ref{sec-pretrend},
other checks are conducted to ensure the robustness of the main
\hyperref[sec-results]{results}.

\subsection{Alternative Estimators}\label{alternative-estimators}

Alternative estimators such as the difference-in-differences (DiD),
synthetic control (SCM) and synthetic difference-in-differences
(SDiD)\footnote{A novel estimator proposed by Arkhangelsky et al.
  (\citeproc{ref-Arkhangelsky2021}{2021}) that combines the DiD and SCM.}
are used to cross-check the DM-LFM \hyperref[sec-results]{results} in
the main analysis. The results using these alternative estimators are
reported in Appendix \ref{sec-alternative} alongside the main results
using the DM-LFM. Although the alternative estimators cannot produce
valid inference as discussed in the \hyperref[sec-empirical]{Empirical
Strategy}, they provide comparable ATT estimates to the DM-LFM results.
This suggests our results are robust.

\subsection{Re-estimation with Earlier Treatment
Time}\label{sec-main-early}

One may suspect that the BoE might have anticipated the indemnity, in
which case Assumption \ref{asp-noant} would be violated. Therefore, the
main analysis is replicated with an earlier treatment time of 2004 to
test the main \hyperref[sec-results]{results}' sensitivity to the
possible anticipation effect. The results are presented in Appendix
\ref{sec-early}. It can be seen that the point estimates are stable,
which indicates good robustness of our results, despite lower
statistical significance resulting from the short pre-treatment period.

\subsection{Identification of Selection Bias - a Parameter Location
Problem}\label{sec-bias}

As explained in the \hyperref[sec-empirical]{Empirical Strategy},
although the DM-LFM estimator overcomes many shortcomings of other
estimators, its estimates are still prone to \emph{selection bias} due
to the little information about central bank's sensitivity to losses
(\(\alpha\)) that can be extracted from the \emph{pre-treatment}
outcomes, despite the attempt to address it by controlling for relevant
covariates.

Recall from the \hyperref[model-setup]{Model Setup}, the period utility
function for central bank (\(B\)):

\[
U_{Bt} = -(\pi_t-2)^2 + \alpha(1-x_t)\min\{p_t,0\}
\]

where

\[
p_t=-\psi(i_t-2)r_t
\]

Before QE in 2009, the risk level chosen by \(B\) was always 0
(\(r_0=0\)). This means that abnormal profit before QE would also be 0
and the central bank's sensitivity (\(\alpha\)) would be eliminated from
the utility function \(U_{Bt}\):

\begin{align*}
p_t&=-\psi(i_t-2)\times0=0\\
U_{Bt}&= -(\pi_t-2)^2 + \alpha(1-x_t)\min\{0,0\} \\
&=-(\pi_t-2)^2
\end{align*}

More importantly, \(\alpha\) \emph{only} affects the system through the
central bank's utility function (\(U_B\)). This means that information
about \(\alpha\) is not extractable from pre-treatment outcomes.
Unfortunately, the fact that central bank sensitivity (\(\alpha\))
determines the \emph{direction} of the selection bias makes it a problem
impossible to circumvent empirically.

We first define selection bias:

\begin{restatable}[Selection bias]{defi}{selbias}
\label{defi-selbias}
Selection bias is defined as the baseline difference between the control and treatment units in the untreated potential outcome of profits.
$$
\text{Bias}_t(\alpha,\rho)=p_t(x=0|x=1,\alpha,\rho)-\mathbb{E}[p_t(x=0)|x=0]
$$
\end{restatable}

According to this definition, we can plot the direction (in
Figure~\ref{fig-bias-sign}) and size (in Figure~\ref{fig-bias}) of
selection bias with respect to \(\alpha\) and \(\rho\) by comparing
their untreated potential outcomes of treated units to the mean outcome
of the control group (red area in Figure~\ref{fig-indemnity}).
Figure~\ref{fig-bias-sign} and Figure~\ref{fig-bias} suggest that, in
the deflationary period (\(t=1\)), the selection bias is relatively
large but primarily \emph{negative}, which makes our estimates more
\emph{conservative}; in the inflationary period (\(t=2\)), the selection
bias is relatively small, but varies in direction.
Figure~\ref{fig-bias-sign} shows, that when \(\alpha\) is high and
\(\rho\) is low (as in the \emph{blue} area of the right panel), the
bias is \emph{positive and conservative}, since the effect is expected
to be negative (see Figure~\ref{fig-p2-comp}).

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-bias-sign-1.pdf}}

}

\caption{\label{fig-bias-sign}Sign of selection bias with respect to
\(\rho\) and \(\alpha\)}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-bias-1.pdf}}

}

\caption{\label{fig-bias}Size of selection bias with respect to \(\rho\)
and \(\alpha\)}

\end{figure}%

Thanks to the theoretical model, there is an \emph{indirect} test that
is sufficient to prove that the UK locates in this blue area of
conservative bias. Figure~\ref{fig-i1} (restated below) shows that
\emph{only} for the area where \(i_1(x=0)=0\) (light blue in left
panel), a significantly \emph{negative} impact of indemnity on monetary
policy is expected. More importantly, this estimate is convincingly
\emph{downward/conservatively} biased because the control group (on the
right of each panel) is expected to have lower \(i_1\) (denoted by
darker blue) at the baseline.

\centerstart

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/unnamed-chunk-2-1.pdf}}

\centerend

Therefore, it is true that:

\begin{restatable}[Supplementary test of downward bias]{prp}{biastest}
\label{prp-biastest}
An empirical supplementary test that suggests the UK adopted a significantly more expansionary monetary policy due to the indemnity in the deflationary period is sufficient to prove that the estimates of the indemnity's impact on profits are conservative.
\end{restatable}

Therefore, additional DM-LFM analyses are conducted as supplementary
tests. The supplementary tests use two outcome variables to measure
monetary policy: central bank policy interest rate as a direct
measurement, and the central bank liabilities as an indirect
measurement. Central bank liabilities (as percentage of GDP) are used as
a good approximation of the \emph{monetary base}, a tool that central
banks use to affect market interest rates (\citeproc{ref-Rule2015}{Rule,
2015}). Moreover, central bank liabilities are solely decided by central
bank themselves, unaffected by commercial bank lending decisions (unlike
other indicators of money supply such as M2) or asset price fluctuations
(unlike central bank assets). Hence, higher (lower) liabilities relative
to GDP are a good indicator of expansionary (contractionary) monetary
policy.

The results for supplementary tests are shown in
Table~\ref{tbl-supp}\footnote{Note the observations for the interest
  rate estimation are fewer because the data for new Euro Area members
  are not available from FRED (\citeproc{ref-FRED2024}{2024}).}.
Additional plots are available in Appendix \ref{sec-supp}. Recall that
the estimates from these supplementary tests are \emph{conservatively}
biased. This implies that the indemnity is estimated to have
significantly reduced the BoE policy interest rate by at least 2.7
percentage points in the deflationary period (2009-2021); this suggests
the UK adopted a significantly more expansionary monetary policy due to
the indemnity. Moreover, the indemnity is also estimated to have
increased the size of the BoE liabilities (interpreted as UK monetary
base) by at least 11\% of GDP, albeit statistically insignificant.
Nevertheless, the positive coefficient can be interpreted as
complementary to the interest rate results.

\begin{table}[H]

\caption{\label{tbl-supp}Supplementary DM-LFM results for impact of
indemnity on monetary policy in the deflationary period (2009-2021)}

\centering{

\centering
\resizebox{\ifdim\width>\linewidth 1\linewidth\else\width\fi}{!}{
\begin{talltblr}[         %% tabularray outer open
entry=none,label=none,
note{}={+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001},
note{ }={95\% equal-tailed Credible Intervals in square brackets.},
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]},
hline{2}={1-3}{solid, black, 0.05em},
hline{10}={1-3}{solid, black, 0.05em},
hline{1}={1-3}{solid, black, 0.1em},
hline{13}={1-3}{solid, black, 0.1em},
column{2-3}={}{halign=c},
column{1}={}{halign=l},
}                     %% tabularray inner close
& Interest Rate & BoE Liabilities \\
ATT & \num{-3.239}*** & \num{9.226} \\
& [\num{-3.442}, \num{-3.023}] & [\num{-19.195}, \num{38.461}] \\
Publicly traded & \num{0.000} & \num{-0.189} \\
& [\num{-0.000}, \num{0.000}] & [\num{-1.196}, \num{0.608}] \\
Euro Area & \num{-0.215}*** & \num{0.080} \\
& [\num{-0.264}, \num{-0.168}] & [\num{-0.814}, \num{1.041}] \\
Reappointability & \num{-0.000} & \num{0.038} \\
& [\num{-0.000}, \num{0.000}] & [\num{-0.196}, \num{0.382}] \\
Observations & \num{414} & \num{586} \\
Treated Units & \num{1} & \num{1} \\
Control Units & \num{16} & \num{23} \\
\end{talltblr}
}

}

\end{table}%

Therefore, evidence suggests that the potential selection bias in the
main \hyperref[sec-results]{results} from missing information about the
central bank's sensitivity to losses (\(\alpha\)) is
\emph{conservative.} Moreover, this means that the UK locates in the
\emph{blue} area in the right panel of Figure~\ref{fig-bias} (restated
below), where the government (\(G\)) is relatively insensitive to fiscal
deficit (low \(\rho\)) but the central bank (\(\alpha\)) is relatively
sensitive to financial losses high (\(\alpha\)).

\centerstart

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/unnamed-chunk-3-1.pdf}}

\centerend

\section{Discussion - Where Are Countries
Located?}\label{sec-discussion}

Recall Proposition \ref{prp-belt} that, the effects of the indemnity on
profits are strongest along a belt of effects as shown in
Figure~\ref{fig-belt} (restated below). The empirical
\hyperref[sec-results]{results} suggest that the indemnity against QE
losses received by the BoE has substantively increased its profits
during the deflationary period (2009-2021) when expansionary monetary
policy was concerned, and exacerbated its losses during the inflationary
period (2022-23) when contractionary monetary policy was implemented.
This means the UK is likely located on the belt of effect.

\centerstart

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/unnamed-chunk-4-1.pdf}}

\centerend

This paper further argues that the UK is located in the \emph{upper}
part of the belt, where \(\alpha\) is high and \(\rho\) is not too low,
and the approximate locations of the UK, US and Euro Area countries are
shown in Figure~\ref{fig-location}.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-location-1.pdf}}

}

\caption{\label{fig-location}Approximate locations of the UK, US and
Euro Area countries}

\end{figure}%

There are qualitative accounts for why the BoE is likely the most
sensitive to losses (highest \(\alpha\)), and why Euro Area is the least
sensitive among the three. Diessner (\citeproc{ref-Diessner2023}{2023})
documents that the BoE is the \emph{least} independent from the Treasury
among the mentioned central banks, for two reasons. First, the inflation
target of the BoE is set by the Treasury, whereas that of the Fed and
ECB are set by themselves (\citeproc{ref-Svensson2010}{Svensson, 2010}).
Second, the BoE only enjoys a small capital base and lacks any capacity
to strengthen its capital position
(\citeproc{ref-Diessner2023}{Diessner, 2023}). As such, the BoE is both
politically and financially dependent on the Treasury, which results in
high sensitivity to losses. This high sensitivity is also revealed by
the fact that the BoE would have \emph{not implemented QE at all}
without indemnity according to interviews of former MPC members
(\citeproc{ref-Diessner2023}{Diessner, 2023}). This confirms our
location of the BoE in the upper part of the ``belt of effect'' where no
QE would be implemented without indemnity, and considerable QE was
carried out under treatment. On the contrary, the Euro Area central
banks are the least financially sensitive because their monetary policy
is dictated by the European Central Bank (ECB), which is among the most
independent central banks (\citeproc{ref-Diessner2023}{Diessner, 2023}).
The ECB makes monetary decisions free of political pressure from
national governments or a non-existent Eurozone treasury
(\citeproc{ref-Goodhart1998}{Goodhart, 1998}). This independence is
exemplified by the ECB's discretionary doubling of its capital base as a
signal to national governments that it would not ``{[}embark{]} on a
quid pro quo'' in monetary decision making
(\citeproc{ref-Diessner2023}{Diessner, 2023}). Therefore, it is
convincing to conclude that the BoE is the most sensitive to losses,
followed by the Federal Reserve and the Euro Area central banks.

The order of fiscal conservatism (\(\rho\)) in Figure~\ref{fig-location}
is supported by indirect evidence of historical budget records in
Figure~\ref{fig-budget}. While it is commonsensical that the Euro Area
has historically run the smallest budget deficit due to 1) strict EU
fiscal rules and 2) impossibility of national-level monetary financing
of deficits (\citeproc{ref-Frieden2017}{Frieden \& Walter, 2017};
\citeproc{ref-PisaniFerry2012}{Pisani-Ferry, 2012}), it may be
surprising before seeing the evidence that the UK is \emph{less}
fiscally conservative than the US, despite the advertisement of
austerity under the Conservative government from 2010 onward
(\citeproc{ref-Reeves2013}{Reeves et al., 2013}). In fact, the UK
consistently ran a larger budget deficit than the US before the
indemnity was agreed in 2009, and continued to maintain a larger deficit
than the US as a proportion of GDP until 2016, with the exception of
2011. Therefore, the UK is believed to be the most fiscally liberal,
followed by the US and Euro Area countries.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-budget-1.pdf}}

}

\caption{\label{fig-budget}Budget surplus (deficit) of the UK, US and
Euro Area over time (Source:
\href{https://tradingeconomics.com/}{Trading Economics})}

\end{figure}%

\section{Conclusion}\label{sec-conclusion}

This paper presents a theoretical framework to analyse the causes and
impacts of fiscal indemnity for central banks' quantitative
easing-related losses. The predicted impact of indemnity on central bank
profitability is empirically tested with the UK case study. Findings
indicate that the indemnity granted by the UK government significantly
boosted the Bank of England's profits during the deflationary period
following the 2007-08 Global Financial Crisis. However, since
inflationary pressures emerged in 2022, the indemnity has exacerbated
the Bank's losses. The theoretical and empirical findings fill relevant
gaps in the literature on central bank loss coverage.

Nonetheless, the British experience should not be generalised. The
theoretical model suggests that the pronounced effects in the British
case are likely due to the Bank of England's high sensitivity to losses
and the UK government's moderate fiscal liberalism. For countries that
did not adopt indemnity due to stronger fiscal conservatism, the profit
gains during the deflationary period would have been weaker, and the
impact during the inflationary period would depend on the central bank's
sensitivity to losses. For central banks with lower sensitivity to
losses, the indemnity might have even mitigated losses under
inflationary pressure.

Furthermore, this paper contributes to future policy evaluation and
institutional design by highlighting the \emph{heterogeneity} in the
public finance-price stability trade-off. While the theoretical model
aligns with the mainstream economic literature in recognising the
benefits of indemnity for price stability, these benefits vary
significantly between countries that self-select into indemnity and
those that do not. While the indemnity may help tackle deflationary
pressures in cases like the UK, it contributes little to suppressing
inflation. The reverse is true for countries that do not adopt
indemnity.

There are several limitations to this paper that future research could
address. First, the empirical analysis is limited to a single treated
case (the UK). Future studies could examine similar cases, such as
Canada and New Zealand, which have recently adopted QE and similar
indemnity agreements, as more data become available. Secondly, the
central bank-held bond maturity is a good, if not better, measurement
for monetary policy in the supplementary test evaluating the effect of
indemnity on the depth of QE. However, its inclusion in this study was
beyond the scope due to time constraints in data collection. Future
research could explore these aspects more thoroughly.

\begin{comment}
%TC:ignore
\end{comment}

\newpage

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-Abadie2021}
Abadie, A. (2021). Using synthetic controls: Feasibility, data
requirements, and methodological aspects. \emph{Journal of Economic
Literature}, \emph{59}(2), 391--425.
\url{https://doi.org/10.1257/jel.20191450}

\bibitem[\citeproctext]{ref-Abadie2003}
Abadie, A., \& Gardeazabal, J. (2003). The economic costs of conflict: A
case study of the basque country. \emph{American Economic Review},
\emph{93}(1), 113--132. \url{https://doi.org/10.1257/000282803321455188}

\bibitem[\citeproctext]{ref-Alesina1997}
Alesina, A. (1997). \emph{Political cycles and the macroeconomy}. MIT
Press.

\bibitem[\citeproctext]{ref-Alesina2010}
Alesina, A., \& Stella, A. (2010). The politics of monetary policy.
\emph{NBER Working Paper Series}, \emph{15856}.
\url{https://doi.org/10.3386/w15856}

\bibitem[\citeproctext]{ref-R-synthdid}
Arkhangelsky, D. (2023). \emph{Synthdid: Synthetic
difference-in-difference estimation}.
\url{https://github.com/synth-inference/synthdid}

\bibitem[\citeproctext]{ref-Arkhangelsky2021}
Arkhangelsky, D., Athey, S., Hirshberg, D. A., Imbens, G. W., \& Wager,
S. (2021). Synthetic difference-in-differences. \emph{American Economic
Review}, \emph{111}(12), 4088--4118.
\url{https://doi.org/10.1257/aer.20190159}

\bibitem[\citeproctext]{ref-Barro1983}
Barro, R. J., \& Gordon, D. B. (1983). Rules, discretion and reputation
in a model of monetary policy. \emph{Journal of Monetary Economics},
\emph{12}(1), 101--121.

\bibitem[\citeproctext]{ref-Barwell2016}
Barwell, R. (2016). Monetary dominance. In \emph{Macroeconomic policy
after the crash} (pp. 357--375). Palgrave Macmillan UK.
\url{https://doi.org/10.1057/978-1-137-51592-6_12}

\bibitem[\citeproctext]{ref-Bassetto2013}
Bassetto, M., \& Messer, T. (2013). Fiscal consequences of paying
interest on reserves. \emph{Fiscal Studies}, \emph{34}(4), 413--436.
\url{https://doi.org/10.1111/j.1475-5890.2013.12014.x}

\bibitem[\citeproctext]{ref-BBC2022}
BBC. (2022, October 13). \emph{How much market chaos did the mini-budget
cause?} (Reality Check team, Ed.). Retrieved August 12, 2024, from
\url{https://www.bbc.com/news/63229204}

\bibitem[\citeproctext]{ref-Beckerman1997}
Beckerman, P. (1997). Central-bank decapitalization in developing
economies. \emph{World Development}, \emph{25}(2), 167--178.
\url{https://doi.org/10.1016/s0305-750x(96)00096-4}

\bibitem[\citeproctext]{ref-Bell2023}
Bell, S., Chui, M., Gomes, T., Moser-Boehm, P., \& Tejada, A. P. (2023).
\emph{Why are central banks reporting losses? Does it matter?} (Research
Report 68). BIS. Retrieved August 1, 2024, from
\url{https://www.bis.org/publ/bisbull68.pdf}

\bibitem[\citeproctext]{ref-Bernhard1998}
Bernhard, W. (1998). A political explanation of variations in central
bank independence. \emph{American Political Science Review},
\emph{92}(2), 311--327.

\bibitem[\citeproctext]{ref-Bernhard2002}
Bernhard, W., Broz, J. L., \& Clark, W. R. (2002). The political economy
of monetary institutions. \emph{International Organization},
\emph{56}(4), 693--723.

\bibitem[\citeproctext]{ref-Blanchard2023}
Blanchard, O. J., \& Bernanke, B. S. (2023). What caused the US
pandemic-era inflation? \emph{NBER Working Paper Series}, \emph{31417}.
\url{https://doi.org/10.3386/w31417}

\bibitem[\citeproctext]{ref-Bloomberg2024}
Bloomberg. (2024, February 14). \emph{{UK} refuses to publish {QE}
indemnity due to {``market sensitivities''}}. Bloomberg.com. Retrieved
July 30, 2024, from
\url{https://www.bloomberg.com/news/articles/2024-02-14/uk-refuses-to-publish-qe-indemnity-due-to-market-sensitivities}

\bibitem[\citeproctext]{ref-Bonam2024}
Bonam, D., Ciccarelli, M., \& Gomes, S. (2024). Challenges for monetary
and fiscal policy interactions in the postpandemic era. \emph{ECB
Occasional Paper Series}, \emph{337}.
\url{https://doi.org/10.2866/94499}

\bibitem[\citeproctext]{ref-Bunea2016}
Bunea, D., Karakitsos, P., Merriman, N., \& Studener, W. (2016). Profit
distribution and loss coverage rules for central banks. \emph{ECB
Occasional Paper Series}, \emph{169}.
\url{https://www.ecb.europa.eu/pub/pdf/scpops/ecbop169.en.pdf}

\bibitem[\citeproctext]{ref-Calomiris2023}
Calomiris, C. W. (2023). Fiscal dominance and the return of
zero-interest bank reserve requirements. \emph{Review}, \emph{105}(4).
\url{https://doi.org/10.20955/r.105.223-33}

\bibitem[\citeproctext]{ref-Card2000}
Card, D., \& Krueger, A. B. (2000). Minimum wages and employment: A case
study of the fast-food industry in new jersey and pennsylvania: reply.
\emph{American Economic Review}, \emph{90}(5), 1397--1420.
\url{https://doi.org/10.1257/aer.90.5.1397}

\bibitem[\citeproctext]{ref-Cecchetti2024}
Cecchetti, S. G., \& Hilscher, J. (2024). Fiscal consequences of central
bank losses. \emph{NBER Working Paper Series}, \emph{32478}.
\url{https://doi.org/10.3386/w32478}

\bibitem[\citeproctext]{ref-Chaboud2013}
Chaboud, A., \& Leahy, M. (2013). \emph{Foreign central bank remittance
practices}. Retrieved July 30, 2024, from
\url{https://www.federalreserve.gov/monetarypolicy/files/FOMC20130308memo09.pdf}

\bibitem[\citeproctext]{ref-Conley2011}
Conley, T. G., \& Taber, C. R. (2011). Inference with {``difference in
differences''} with a small number of policy changes. \emph{Review of
Economics and Statistics}, \emph{93}(1), 113--125.
\url{https://doi.org/10.1162/rest_a_00049}

\bibitem[\citeproctext]{ref-Cukierman2011}
Cukierman, A. (2011). Central bank finances and independence -- how much
capital should a CB have? In S. M. \& P. Sinclair (Ed.), \emph{The
capital needs of central banks} (pp. 33--46). Routledge.
\url{https://doi.org/10.4324/9780203841037}

\bibitem[\citeproctext]{ref-Dalton2005}
Dalton, J., \& Dziobek, C. (2005). \emph{Central bank losses and
experiences in selected countries}.

\bibitem[\citeproctext]{ref-DelNegro2015}
Del Negro, M., \& Sims, C. A. (2015). When does a central bank׳s balance
sheet require fiscal support? \emph{Journal of Monetary Economics},
\emph{73}, 1--19. \url{https://doi.org/10.1016/j.jmoneco.2015.05.001}

\bibitem[\citeproctext]{ref-Diessner2023}
Diessner, S. (2023). The political economy of monetary-fiscal
coordination: Central bank losses and the specter of central bankruptcy
in europe and japan. \emph{Review of International Political Economy},
\emph{31}(3), 1099--1121.
\url{https://doi.org/10.1080/09692290.2023.2295373}

\bibitem[\citeproctext]{ref-theevol1991}
Downes, P., \& Vaez-Zadeh, R. (1991). \emph{The evolving role of central
banks}. Internaitonal Monetary Fund.
\url{https://doi.org/10.5089/9781557751850.071}

\bibitem[\citeproctext]{ref-Dreher2008}
Dreher, A., Sturm, J.-E., \& Haan, J. de. (2008). Does high inflation
cause central bankers to lose their job? Evidence based on a new data
set. \emph{European Journal of Political Economy}, \emph{24}(4),
778--787. \url{https://doi.org/10.1016/j.ejpoleco.2008.04.001}

\bibitem[\citeproctext]{ref-FernandezAlbertos2015}
Fernández-Albertos, J. (2015). The politics of central bank
independence. \emph{Annual Review of Political Science}, \emph{18}(1),
217--237. \url{https://doi.org/10.1146/annurev-polisci-071112-221121}

\bibitem[\citeproctext]{ref-ft150bn}
Financial Times. (2023a, July). \emph{{UK} government faces £150bn bill
to cover {Bank} of {England}'s {QE} losses}. Financial Times. Retrieved
July 29, 2024, from
\url{https://www.ft.com/content/ee8e33ee-e16e-459b-af32-5709db6874de}

\bibitem[\citeproctext]{ref-ft-indem-start}
Financial Times. (2023b, August 28). \emph{The growing fiscal drag of
the {BoE}'s {QE} indemnity}. Financial Times. Retrieved July 29, 2024,
from
\url{https://www.ft.com/content/8ba03ab6-28e9-44f0-b90d-9ee617c27597}

\bibitem[\citeproctext]{ref-ft-admit-higher-losses}
Financial Times. (2023c, December). \emph{Bank of {England} losses on
{QE} greater than other central banks, says ex-rate setter}. Financial
Times. Retrieved July 29, 2024, from
\url{https://www.ft.com/content/a411ebdf-1086-4537-af15-c6c5878353aa}

\bibitem[\citeproctext]{ref-FRED2024}
FRED. (2024). \emph{Federal reserve economic data} {[}dataset{]}.
St.Louis Fed. \url{https://fred.stlouisfed.org/}

\bibitem[\citeproctext]{ref-Frieden2017}
Frieden, J., \& Walter, S. (2017). Understanding the political economy
of the eurozone crisis. \emph{Annual Review of Political Science},
\emph{20}(1), 371--390.
\url{https://doi.org/10.1146/annurev-polisci-051215-023101}

\bibitem[\citeproctext]{ref-Goncharov2023}
Goncharov, I., Ioannidou, V., \& Schmalz, M. C. (2023). (Why) Do Central
Banks Care about Their Profits? \emph{The Journal of Finance},
\emph{78}(5), 2991--3045. \url{https://doi.org/10.1111/jofi.13257}

\bibitem[\citeproctext]{ref-Goodhart1998}
Goodhart, C. A. E. (1998). The two concepts of money: Implications for
the analysis of optimal currency areas. \emph{European Journal of
Political Economy}, \emph{14}(3), 407--432.
\url{https://doi.org/10.1016/s0176-2680(98)00015-9}

\bibitem[\citeproctext]{ref-Hall2015}
Hall, R. E., \& Reis, R. (2015). Maintaining central-bank financial
stability under new-style central banking. \emph{NBER Working Paper
Series}, \emph{21173}. \url{https://doi.org/10.3386/w21173}

\bibitem[\citeproctext]{ref-Hallerberg2002}
Hallerberg, M. (2002). Veto players and the choice of monetary
institutions. \emph{International Organization}, \emph{56}(4), 775--802.

\bibitem[\citeproctext]{ref-Hilscher2015}
Hilscher, J., Raviv, A., \& Reis, R. (2015). \emph{Measuring the market
value of central bank capital}. Brandeis University; Columbia
University.

\bibitem[\citeproctext]{ref-Hinterlang2022}
Hinterlang, N., \& Hollmayr, J. (2022). Classification of monetary and
fiscal dominance regimes using machine learning techniques.
\emph{Journal of Macroeconomics}, \emph{74}, 103469.
\url{https://doi.org/10.1016/j.jmacro.2022.103469}

\bibitem[\citeproctext]{ref-HMTreasury2014}
HM Treasury. (2014). \emph{Budget 2014} (HC 1104). HM Treasury.
\url{https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/293759/37630_Budget_2014_Web_Accessible.pdf}

\bibitem[\citeproctext]{ref-HCTC2024}
House of Commons Treasury Committee. (2024). \emph{Quantitative
tightening fifth report of session 2023--24: Report, together with
formal minutes relating to the report}. Retrieved July 30, 2024, from
\url{https://committees.parliament.uk/publications/43233/documents/215145/default/}

\bibitem[\citeproctext]{ref-Joyce2012}
Joyce, M., Miles, D., Scott, A., \& Vayanos, D. (2012). Quantitative
easing and unconventional monetary policy --- an introduction. \emph{The
Ecocnomic Journal}, \emph{122}(564), F271--F288. Retrieved July 30,
2024, from \url{http://www.jstor.org/stable/23324224}

\bibitem[\citeproctext]{ref-Kydland1977}
Kydland, F. E., \& Prescott, E. C. (1977). Rules rather than discretion:
The inconsistency of optimal plans. \emph{Journal of Political Economy},
\emph{85}(3), 473--491.

\bibitem[\citeproctext]{ref-Landes2013}
Landes, X. (2013). Moral hazard. In \emph{Encyclopedia of corporate
social responsibility} (pp. 1715--1722). Springer Berlin Heidelberg.
\url{https://doi.org/10.1007/978-3-642-28036-8_47}

\bibitem[\citeproctext]{ref-Lohmann1997}
Lohmann, S. (1997). Partisan control of the money supply and
decentralized appointment powers. \emph{European Journal of Political
Economy}, \emph{13}(2), 225--246.

\bibitem[\citeproctext]{ref-Lohmann2008}
Lohmann, S. (2008). \emph{The non-politics of monetary policy}.

\bibitem[\citeproctext]{ref-Long2024}
Long, J., \& Fisher, P. (2024). \emph{Central bank profit distribution
and recapitalisation} (Research Report 1069). Bank of England. Retrieved
August 1, 2024, from
\url{https://www.bankofengland.co.uk/-/media/boe/files/working-paper/2024/central-bank-profit-distribution-and-recapitalisation.pdf}

\bibitem[\citeproctext]{ref-Lonnberg2008}
Lonnberg, A., \& Stella, P. (2008). Issues in central bank finance and
independence {[}IMF Working Paper{]}. \emph{IMF Working Paper},
\emph{08/37}. Retrieved August 1, 2024, from
\url{https://papers.ssrn.com/abstract=1094219}

\bibitem[\citeproctext]{ref-Mackenzie1996}
Mackenzie, G. A., \& Stella, P. (1996). \emph{Quasi-fiscal operations of
public financial institutions} (G. A. Mackenzie \& P. Stella, Eds.;
Research Report Occasional Paper No. 142; Occasional Papers).
International Monetary Fund; International Monetary Fund.

\bibitem[\citeproctext]{ref-MacKinnon2023}
MacKinnon, J. G., Nielsen, M. Ø., \& Webb, M. D. (2023a). Cluster-robust
inference: A guide to empirical practice. \emph{Journal of
Econometrics}, \emph{232}(2), 272--299.
\url{https://doi.org/10.1016/j.jeconom.2022.04.001}

\bibitem[\citeproctext]{ref-MacKinnon2023a}
MacKinnon, J. G., Nielsen, M. Ø., \& Webb, M. D. (2023b). Fast and
reliable jackknife and bootstrap methods for cluster‐robust inference.
\emph{Journal of Applied Econometrics}, \emph{38}(5), 671--694.
\url{https://doi.org/10.1002/jae.2969}

\bibitem[\citeproctext]{ref-MacKinnon2016}
MacKinnon, J. G., \& Webb, M. D. (2016). Wild bootstrap inference for
wildly different cluster sizes. \emph{Journal of Applied Econometrics},
\emph{32}(2), 233--254. \url{https://doi.org/10.1002/jae.2508}

\bibitem[\citeproctext]{ref-MacKinnon2018}
MacKinnon, J. G., \& Webb, M. D. (2018). The wild bootstrap for few
(treated) clusters. \emph{The Econometrics Journal}, \emph{21}(2),
114--135. \url{https://doi.org/10.1111/ectj.12107}

\bibitem[\citeproctext]{ref-Markiewicz2001}
Markiewicz, M. (2001). Quasi-fiscal operations of central banks in
transition economies. \emph{BOFIT Discussion Paper}, \emph{2/2001}.
\url{https://doi.org/10.2139/ssrn.1016035}

\bibitem[\citeproctext]{ref-Molho1989}
Molho, L. (1989). European financial integration and revenue from
seignorage: The case of italy. In \emph{SSRN} (884765). Retrieved July
31, 2024, from \url{https://papers.ssrn.com/abstract=884765}

\bibitem[\citeproctext]{ref-Mukherjee2008}
Mukherjee, B., \& Singer, D. A. (2008). Monetary institutions,
partisanship, and inflation targeting. \emph{International
Organization}, \emph{62}(02).
\url{https://doi.org/10.1017/s0020818308080119}

\bibitem[\citeproctext]{ref-Munoz2007}
Muñoz, S. (2007). \emph{{Central Bank Quasi-Fiscal Losses and High
Inflation in Zimbabwe: A Note}} (IMF Working Papers 2007/098).
International Monetary Fund.
\url{https://ideas.repec.org/p/imf/imfwpa/2007-098.html}

\bibitem[\citeproctext]{ref-ONS2024}
Office for National Statistics. (2024). \emph{Public sector finances
tables 1 to 10: Appendix a} {[}dataset{]}. Retrieved August 11, 2024,
from
\url{https://www.ons.gov.uk/economy/governmentpublicsectorandtaxes/publicsectorfinance/datasets/publicsectorfinancesappendixatables110}

\bibitem[\citeproctext]{ref-Pang2021}
Pang, X., Liu, L., \& Xu, Y. (2021). A Bayesian Alternative to Synthetic
Control for Comparative Case Studies. \emph{Political Analysis},
\emph{30}(2), 269--288. \url{https://doi.org/10.1017/pan.2021.22}

\bibitem[\citeproctext]{ref-PisaniFerry2012}
Pisani-Ferry, J. (2012). The euro crisis and the new impossible trinity.
In \emph{Bruegel Policy Contribution} (Research Report 2012/01).
Bruegel.

\bibitem[\citeproctext]{ref-Pringle1999}
Pringle, R., \& Turner, M. (1999). The relationship between the european
central bank and the national central banks within the eurosystem. In
\emph{From EMS to EMU: 1979 to 1999 and beyond} (pp. 231--255). Palgrave
Macmillan UK. \url{https://doi.org/10.1007/978-1-349-27745-2_16}

\bibitem[\citeproctext]{ref-Reeves2013}
Reeves, A., Basu, S., McKee, M., Marmot, M., \& Stuckler, D. (2013).
Austere or not? UK coalition government budgets and health inequalities.
\emph{Journal of the Royal Society of Medicine}, \emph{106}(11),
432--436. \url{https://doi.org/10.1177/0141076813501101}

\bibitem[\citeproctext]{ref-Reis2013}
Reis, R. (2013). The mystique surrounding the central bank's balance
sheet, applied to the european crisis. \emph{American Economic Review},
\emph{103}(3), 135--140. \url{https://doi.org/10.1257/aer.103.3.135}

\bibitem[\citeproctext]{ref-Reis2015}
Reis, R. (2015). Different types of central bank insolvency and the
central role of seignorage. \emph{NBER Working Paper Series},
\emph{21226}. \url{https://doi.org/10.3386/w21226}

\bibitem[\citeproctext]{ref-Rogoff1985}
Rogoff, K. (1985). The optimal degree of commitment to an intermediate
monetary target. \emph{The Quarterly Journal of Economics},
\emph{100}(4), 1169--1189.

\bibitem[\citeproctext]{ref-Rule2015}
Rule, G. (2015). \emph{Understanding the central bank balance sheet.
ISSN} (Research Report 1756-7270). Bank of England.
\url{https://www.bankofengland.co.uk/-/media/boe/files/ccbs/resources/understanding-the-central-bank-balance-sheet.pdf}

\bibitem[\citeproctext]{ref-SCIP2024}
S\&P Capital IQ Pro. (2024). {[}dataset{]}.
\url{https://www-capitaliq-spglobal-com}

\bibitem[\citeproctext]{ref-Stella1997}
Stella, P. (1997). Do central banks need capital. In \emph{IMF Working
Paper} (83). IMF.

\bibitem[\citeproctext]{ref-Stella2005}
Stella, P. (2005). Central bank financial strength, transparency, and
policy credibility. \emph{IMF Staff Papers}, \emph{52}(2), 335--365.
\url{https://doi.org/10.2307/30035902}

\bibitem[\citeproctext]{ref-Svensson2010}
Svensson, L. E. O. (2010). Inflation targeting. In \emph{Handbook of
monetary economics} (pp. 1237--1302). Elsevier.
\url{https://doi.org/10.1016/b978-0-444-53454-5.00010-4}

\bibitem[\citeproctext]{ref-Sweidan2011}
Sweidan, O. D. (2011). Central bank losses: causes and consequences.
\emph{Asian-Pacific Economic Literature}, \emph{25}(1), 29--42.
\url{https://doi.org/10.1111/j.1467-8411.2011.01281.x}

\bibitem[\citeproctext]{ref-Independent2024}
The Independent. (2024, May 20). \emph{Tory MPs demand review of bank of
england independence} (C. McKeon, Ed.). Retrieved July 30, 2024, from
\url{https://www.independent.co.uk/business/tory-mps-demand-review-of-bank-of-england-independence-b2547407.html}

\bibitem[\citeproctext]{ref-Woodruff2019}
Woodruff, D. M. (2019). To democratize finance, democratize central
banking. \emph{Politics \&Amp; Society}, \emph{47}(4), 593--610.
\url{https://doi.org/10.1177/0032329219879275}

\bibitem[\citeproctext]{ref-WBOD2024}
World Bank Open Data. (2024). {[}dataset{]}.
\url{https://data.worldbank.org/}

\end{CSLReferences}

\appendix
\newpage

\section{Complete Model Derivation and Analysis}\label{sec-model-app}

This appendix presents the full subgame analysis for when the central
bank receives indemnity (\(x=1\)) or not (\(x=0\)) as a supplement to
the \hyperref[sec-theory]{Theory} section.

\subsection{\texorpdfstring{Subgame with Indemnity
(\(x=1\))}{Subgame with Indemnity (x=1)}}\label{sec-model-app-indem}

We start with the simpler case when the government indemnifies the
central bank (\(x=1\)). With backward induction, we first solve for the
second period with the constraint of first period risk level \(r_1\).

The government's second period payoff function is given by:

\[
U_{G2}(x=1)= C(p_2+f_2) + 4 -f_2-i_2 +\epsilon_{d2}+\epsilon_{s2}
\]

The government maximises its expected payoff in the second period by:

\begin{align*}
\frac{\partial}{\partial f_2} EU_{G2}(x=1) &= \frac{\partial C}{\partial (p_2 + f_2)} -1=0 \\
p_2+f_2 &= \left( \frac{\partial C}{\partial (p_2 + f_2)} \right)^{-1}(1)=\rho \\
f_2^*&= \rho -p_2 \\
&=\rho +\psi(i_2-2)r_2
\end{align*}

When the central bank is indemnified (\(x=1\)), the central bank's
second period payoff function is given by:

\begin{align*}
U_{B2}(x=1) &=-(\pi_2-2)^2 \\
&=-(2-f_2-i_2+\epsilon_{d2}-\epsilon_{s2})^2
\end{align*}

Deciding on the level of monetary policy (\(i_2\)) and risk-taking
(\(r_2\)), we take the first order conditions:

w.r.t monetary policy (\(i_2\)):

\begin{align}
\frac{\partial}{\partial i_2} U_{B2}(x=1) &= 2(2-f_2-i_2+\epsilon_{d2}-\epsilon_{s2})=0 \nonumber \\
2-f_2-i_2+\epsilon_{d2}-\epsilon_{s2}&=0 \label{eq-inftarget} \\
i_2^*(x=1) &= 2-f_2+\epsilon_{d2}-\epsilon_{s2} \nonumber
\end{align}

Note Equation (\ref{eq-inftarget}) implies that the indemnified central
bank can always achieve the inflation target at 2\% by adjusting the
monetary policy to the fiscal policy and the shocks.

Substituting \(f_2^*(x=1)\) into \(i_2^*(x=1)\):

\begin{align*}
i^*_2(x=1) &= 2-(\rho +\psi(i_2-2)r_2)+\epsilon_{d2}-\epsilon_{s2} \\
&=2-\rho-\psi i_2r_2+2\psi r_2+\epsilon_{d2}-\epsilon_{s2} \\
(1+\psi r_2)i^*_2(x=1)&=2-\rho+2\psi r_2+\epsilon_{d2}-\epsilon_{s2} \\
i^*_2(x=1) &=\frac{2-\rho+2\psi r_2+\epsilon_{d2}-\epsilon_{s2}}{\psi r_2+1} \\
\end{align*}

For convenience, we denote the frequently used expression
\(2-\rho+\epsilon_{d2}-\epsilon_{s2}\) as \(u\). \(u\) can be conceived
of as the inflationary pressure perceived by the central bank \(B\)
after taking into account fiscal policy. Therefore,

\[
i^*_2(x=1) =\frac{u+2\psi r_2}{\psi r_2+1}
\]

Accordingly, the risk level is either kept the same by central bank
\(B\) or increased to the minimum level that optimal monetary policy
\(i_2\) requires:

\begin{align*}
r_2^*(x=1)&=\max\{r_1, -i^*_2\}=\max\{r_1,\frac{-u+2\psi r_2}{\psi r_2+1}\} \\
&=\max\{r_1,\frac{-(2\psi+1)+\sqrt{(2\psi+1)^2-4\psi u}}{2\psi}\}
\end{align*}

Recall from Equation (\ref{eq-inftarget}) that, in the second period (we
will show it is also true for the first period), an indemnified bank can
maintain the inflation on target by adjusting the monetary policy
according to the fiscal policy. The central bank's utility is at the
maximum of 0 in this case:

\begin{align*}
\pi_2^*(x=1) &= 4-(f_2^*(x=1)+i_2^*(x=1))+\epsilon_{d2}-\epsilon_{s2} \\
&=4-(2+\epsilon_{d2}-\epsilon_{s2})+\epsilon_{d2}-\epsilon_{s2} \\
&=2 \\
U_{B2}(x=1) &=-(\pi_2^*(x=1)-2)^2 \\
&=-(2-2)^2 \\
&=0
\end{align*}

We now turn to the first period of the subgame. Since the government's
first period fiscal policy (\(f_1\)) does not affect the second period,
the government maximises its expected payoff in the first period in a
similar way to the second period:

\begin{align*}
U_{G1}(x=1)&= C(p_1+f_1) + 4 -f_1-i_1 +\epsilon_{d1}+\epsilon_{s1} \\
&= C(p_1+f_1) + 4 -f_1-i_1 -1+0 \\
&= C(p_1+f_1) + 3 -f_1-i_1 \\
\frac{\partial}{\partial f_1} U_{G1}(x=1) &= \frac{\partial C}{\partial (p_1 + f_1)} -1=0 \\
p_1+f_1 &= \left( \frac{\partial C}{\partial (p_1 + f_1)} \right)^{-1}(1)=\rho \\
f_1^*&= \rho -p_1 \\
&=\rho +\psi(i_1-2)r_1
\end{align*}

It can be seen that, for both periods, it is true that \[
f_t(x=1)=\rho-p_t
\]

This is property is known as Proposition \ref{prp-mondom} of monetary
dominance:

\mondom*
%random placeholder

As for the central bank (\(B\)), the first period monetary policy and
risk level do not affect its ability to maintain the inflation target in
the second period since it is indemnified. Therefore, the central bank
also maximises its first period utility by setting the monetary policy
and risk-taking to the optimal level that aims for the 2\% target.
Recall that first period shocks (\(\epsilon_{d1}=-1\),
\(\epsilon_{s1}=0\)) are known to players at the beginning of the game:

\begin{align*}
U_{B1}(x=1) &=-(\pi_1-2)^2 \\
&=-(2-f_1-i_1+\epsilon_{d1}-\epsilon_{s1})^2 \\
&=-(1-f_1-i_1)^2 \\
\frac{\partial}{\partial i_1} U_{B1}(x=1) &= 2(1-f_1-i_1)=0 \\
1-f_1-i_1&=0 \\
i_2^*(x=1) &= 1-f_1
\end{align*}

Substituting \(f_1^*\) into \(i_1^*\), we have the optimal monetary
policy in the first period:

\begin{align*}
i_1^*(x=1) &= 1-(\rho +\psi(i_1-2)r_1) \\
&=1-\rho-\psi i_1r_1+2\psi r_1 \\
(1+\psi r_1)i_1^*(x=1)&=1-\rho+2\psi r_1 \\
i_1^*(x=1)&=\frac{1-\rho+2\psi r_1}{1+\psi r_1}
\end{align*}

When \(i^*_1(x=1)\geq0\) and \(r_1^*=0\), i.e.~\(1-\rho\geq0\),
quantitative easing is not required whatsoever in the first period and
is hence not of interest in this case. We only consider the case when
\(i^*_1(x=1)<0\) and \(r_1^*>0\), i.e.~\(1-\rho<0\) and \(\rho>1\). In
this case, \(r^*_1=-i^*_1\):

\begin{align*}
i_1^*(x=1)&=\frac{1-\rho-2\psi i^*_1}{1-\psi i^*_1} \\
-\psi i^{*2}_1 +i^*_1&=1-\rho-2\psi i^*_1 \\
-\psi i^{*2}_1 +(2\psi+1)i^*_1&=1-\rho \\
i^*_1&=\frac{2\psi+1-\sqrt{(2\psi+1)^2-4\psi(1-\rho)}}{2\psi}<0
\end{align*}

In this case: \[
r^*_1=\frac{-(2\psi+1)+\sqrt{(2\psi+1)^2-4\psi(1-\rho)}}{2\psi}>0
\]

This implies that the central bank can also achieve the 2\% inflation
target in the first period by taking on risk in the first period. Hence,
the central bank's utility in the first period is also 0.

\begin{align*}
\pi_1^*(x=1) &=2 \\
U_{B1}(x=1) &=0
\end{align*}

Hence the second major conclusion of the model:

\stabinf*
%random placeholder

We can now calculate the Government's (\(G\)) (expected) utility from
indemnifying the central bank.

For the first period:

\begin{align*}
U_{G1}(x=1)&=C(p_1+f_1)+g_1 \\
&=C(\rho)+\pi_1+2\epsilon_{s1} \\
&=C(\rho)+2
\end{align*}

For the second period:

\begin{align*}
EU_{G2}(x=1)&=\mathbb{E}[(C(p_2+f_2)+g_1] \\
&=C(\rho)+\mathbb{E}(\pi_2+2\tilde\epsilon_{s2}) \\
&=C(\rho)+2
\end{align*}

Hence, the Government's two-period expected utility from indemnifying
the central bank is:

\begin{align*}
EU_{G}(x=1)&=U_{G1}(x=1)+EU_{G2}(x=1) \\
&=2C(\rho)+4
\end{align*}

\subsection{\texorpdfstring{Subgame without Indemnity
(\(x=0\))}{Subgame without Indemnity (x=0)}}\label{sec-model-app-noindem}

We now consider the more complex case when the government chooses not to
indemnify the central bank (\(x=0\)). With backward induction, we first
solve for the second period with the constraint of first period risk
level \(r_0\).

When the government does not indemnify the central bank (\(x=0\)), the
government's second-period utility function is given by:

\[
U_{G2}(x=0)= C(\max\{p_2,0\}+f_2) + 4 -f_1-i_1 +\epsilon_{d2}+\epsilon_{s2}
\]

The government maximises its expected utility by:

\begin{align*}
\frac{\partial}{\partial f_2} EU_{G2}(x=0) &= \frac{\partial C}{\partial (\max\{p_2,0\} + f_2)} -1=0 \\
\max\{p_2,0\}+f_2 &= \rho \\
f_2^*&= \rho -\max\{p_2,0\} \\
&=\rho +\min\{\psi(i_2-2)r_2,0\}
\end{align*}

When the central bank is not indemnified (\(x=0\)), the central bank's
utility function is given by:

\begin{align*}
U_{B2}(x=0) &=-(\pi_2-2)^2+\alpha\min\{p_2,0\} \\
&=-(2-f_2-i_2+\epsilon_{d2}-\epsilon_{s2})^2-\alpha\psi\max\{(i-2)r_2,0\}
\end{align*}

When \(p>0\) and \(i_2<2\):

The same solution as in the case where \(x=1\) applies.

\begin{align*}
i_2^*(x=0) &= \frac{2-\rho+2\psi r_2+\epsilon_{d2}-\epsilon_{s2}}{\psi r_2+1}=\frac{u+2\psi r_2}{\psi r_2+1}<2 \\
r_2^*(x=0) &= \max\{r_1,-i^*_2\}\\
&=\max\{r_1,\frac{-(2\psi+1)+\sqrt{(2\psi+1)^2-4\psi(1-\rho)}}{2\psi}\}>0
\end{align*}

This implies the 2\% inflation target is met and
\(U_{B2}(x=0,i_2<2)=0\). This requires \(u<2\).

When \(p<0\) and \(i_2>2\):

\begin{align*}
f^*_2(x=0;i_2>2)&=\left( \frac{\partial C}{\partial f_2} \right)^{-1}(1)=\rho \\ \\
U_{B2}(x=0;i_2>2) &=-(2-f_2-i_2+\epsilon_{d2}-\epsilon_{s2})^2-\alpha\psi(i-2)r_2
\end{align*}

It can be shown that, the central bank (\(B\)) prefers a lower level of
risk in the second period \(r_2\) as a higher risk level would increase
the financial loss and no longer help with monetary policy:

\[
\frac{\partial}{\partial r_2} U_{B_2}(x=0,i_2>2) = -\alpha\psi(i_2-2)r_2<0 \\
\]

Therefore, the central bank (\(B\)) chooses the lowest level of risk in
the second period:

\[
r_2(x=0,i_2>2)=r_1
\]

w.r.t monetary policy (\(i\)):

\begin{align}
\frac{\partial}{\partial i_2} U_{B_2}(x=0,i_2>2)&=2(2-f_2-i_2+\epsilon_{d2}-\epsilon_{s2})-\alpha\psi r_1=0 \nonumber \\
f_2+i_2-\epsilon_{d2}+\epsilon_{s2}-2&=-\frac{\alpha\psi r_1}{2} \nonumber \\
i^*_2(x=0) &= -f_2+\epsilon_{d2}-\epsilon_{s2}-\frac{\alpha\psi r_1}{2}+2>2 \label{eq-i2x0}
\end{align}

Substituting \(f^*_2(x=0)\) and \(r_2\) into \(i_2^*(x=0)\):

\begin{align*}
i^*_2 &= -f^*_2+\epsilon_{d2}-\epsilon_{s2}-\frac{\alpha\psi r_1}{2}+2 \\
&=2-\rho+\epsilon_{d2}-\epsilon_{s2}-\frac{\alpha\psi r_1}{2}\\
&=u-\frac{\alpha\psi r_1}{2}
\end{align*}

This requires \(u>2+\frac{\alpha\psi r_1}{2}\). In this case, the
second-period utility of the central bank is:

\[
U_{B2}(x=0,i_2>2)=-(2-f_2^*-i_2^*+\epsilon_{d2}-\epsilon_{s2})^2-\alpha\psi(i^*_2-2)r_1 \\
\]

Recall Equation (\ref{eq-i2x0}), the equation above can be rewritten as:

\begin{align*}
U_{B2}(x=0,i>2)&=-(2-f_2^*-(-f^*_2+\epsilon_{d2}-\epsilon_{s2}-\frac{\alpha\psi r_1}{2}+2)+\epsilon_{d2}-\epsilon_{s2})^2-\alpha\psi(i_2^*-2)r_1 \\
&=-(\frac{\alpha\psi r_1}{2})^2-\alpha\psi r_1(u-\frac{\alpha\psi r_1}{2}-2)
\end{align*}

Therefore, when \(2<u<2+\frac{\alpha\psi r_1}{2}\), \(i_2^*(x=0)=2\). In
other words, there is a range of \(u\) where the central bank (\(B\))
prefers to keep the interest rate neutral in the second period and not
respond to inflationary pressure. In this case, the second-period
utility of the central bank is:

\begin{align*}
U_{B2}(x=0,i_2=2)&=-(2-f^*-2+\epsilon_{d2}-\epsilon_{s2})^2-\alpha\psi(2-2)r_1 \\
&=-(-\rho+\epsilon_{d2}-\epsilon_{s2})^2 \\
&=-(u-2)^2
\end{align*}

The relationship between the second period interest rate (\(r_2^*\)) and
\(u\) is summarised and visualised in Figure~\ref{fig-i0}. It can be
seen that, when the central bank is not indemnified (\(x=0\)) as in
shown by the red line, the function is four-fold: in case of
deflationary pressure (\(u<2\)), the monetary policy linearly decreases
with lower \(u\), until a higher \(r_2\) is required to enable even
lower \(i\). In case of inflationary pressure (\(u>2\)), \(i\) is
briefly stuck at 2 to avoid losses until further inflationary pressure
(higher \(u\)) forces the central bank to embrace tighter monetary
policy (\(i>2\)).

Interest rates for an indemnified counterfactual (blue line) are also
provided for comparison. It is realistically assumed in this graph that
the first period risk level is high when the bank is indemnified
(\(r_1(x=1)>r_1(x=0)\)), which is later proven in Proposition
\ref{prp-prudence}. When this is the case, the interest rates are higher
when the bank is indemnified (\(x=0\)) under deflationary pressure
(\(U<2\)), until a higher \(r_2\) is required, at which point the two
potential outcomes converge. In case of inflationary pressure (\(u>2\)),
the indemnified bank adopts a higher interest rate than the
non-indemnified counterpart, but can be overtaken in the extreme cases
when the inflationary pressure is too high, as further demonstrated in
the \hyperref[sec-simulation]{simulation}.

\begin{figure}

\centering{

\begin{tikzpicture}
\begin{axis}[
    axis lines = left,
    width = 12cm,
    height = 8cm,
    xlabel = \(u\),
    ylabel = \(i_2^*\),
    legend pos=south east,
    legend cell align={left},
]
%Below the red parabola is defined
\tikzmath{\r1 = 0.08113883; \r0 =0.04667465; \a = 4;} 

\addplot [
    domain=(-\r1^2-3*\r1):2.75, 
    samples=100, 
    color=blue,
]
{(x+2*\r1)/(\r1+1)};
\addplot [
    domain=( 2+(\a * \r0)/2 ):2.75, 
    samples=100, 
    color=red,
    ]
    {x-(\a * \r0)/2};
\addplot [
    domain=-1.25:(-\r1^2-3*\r1), 
    samples=100, 
    color=blue,
]
{(3-sqrt(9-4*x))/2};

%Here the blue parabola is defined

\addplot [
    domain=(-\r0^2-3*\r0):2, 
    samples=100, 
    color=red,
    ]
    {(x+2*\r0)/(\r0+1)};
\addplot [
    domain=-1.25:(-\r0^2-3*\r0), 
    samples=100, 
    color=red,
]
{(3-sqrt(9-4*x))/2};

\addplot[mark=none, red] coordinates {(2,2) ( 2+(\a * \r0)/2 ,2)};

\addplot[mark=none, black, thick, dotted] coordinates {(-1.25,2) (2,2)};
\addplot[mark=none, black, thick, dotted] coordinates {(2,-0.3) (2,2)};

% Add legend entries
\addlegendimage{color=blue,solid}
\addlegendentry{with indemnity}
\addlegendimage{color=red,solid}
\addlegendentry{without indemnity}

\end{axis}
\end{tikzpicture}

}

\caption{\label{fig-i0}Illustration of the optimal second-period
interest rate (\(i_2^*\)) with respect to \(u\) (\(\alpha=4\),
\(\rho=1.25\))}

\end{figure}%

We now turn to the first period of this subgame so that we can calculate
the intertemporal optimisation for the central bank's actions.

In the first period, the government's (\(G\)) strategy is the same as in
the second period because its first-period fiscal policy does not affect
the second period: \[
f_1^*(x=0)=\rho +\min\{\psi(i_1-2)r_1,0\}
\]

However, as we discussed in the previous section, we only consider the
case where the deflationary pressure in the first period is so severe
that the 2\% inflation target cannot be met without quantitative easing,
it must be that \(\rho>1\) and \(i^*_1(x=0)\leq0\). This means that no
loss would be made in the first period. Therefore, the first period
fiscal policy can be relaxed to:

\[
f_1^*(x=0)=\rho +\psi(i_1-2)r_1
\]

For the same reason, the central bank's (\(B\)) first period utility is:

\begin{align*}
U_{B1}(x=0)&=-(\pi_1-2)^2 \\
&=-(1-f_1-i_1)^2 \\
&=-(1-f_1+r_1)^2
\end{align*}

It's partial derivative with respect to \(r_1\) is:

\begin{align*}
\frac{\partial}{\partial r_1}U_{B1}(x=0)&=-2(1-f_1+r_1) \\
&=-2(1-(\rho +\psi(i_1-2)r_1)+r_1)\\
\end{align*}

One may notice that, when this first order condition is set to zero, the
solution is exactly the same as \(r^*_1(x=1)\). This means that, when
not considering the second period, an unindemnified central bank (\(B\))
would choose the same level of risk in the first period as an
indemnified central bank (\(B\)). Choosing a higher level of risk would
not offer the central bank (\(B\)) a higher utility in the first period.

Moreover, a higher level of risk in the first period would not offer the
central bank (\(B\)) a higher utility in the second period either.
Recall that the central bank (\(B\)) is indifferent to the level of risk
(\(r_2\)) when there is a deflationary pressure in the second period
(\(u<2\)), as a profit is made in this case and thus excluded from
\(B\)'s utility function; the unindemnified central bank (\(B\)) simply
chooses the optimal monetary policy (\(i_2\)) and the minimum level of
risk required (\(r_2\)). Furthermore, the central bank (\(B\)) strictly
prefers a lower level of risk in the second period when there is an
inflationary pressure in the second period (\(u>2\)). Therefore, the
central bank (\(B\)) never prefers a higher level of risk in the second
period.

Knowing that choosing a higher level of risk in the first period
(\(r_1\)) would not offer the central bank (\(B\)) a higher utility in
either period, and a similar reasoning can be applied to the second
period risk level (\(r_2\)), we have reached the third major finding of
the model:

\prudence*
%random placeholder

Recall the determinants of inflation in period 1:

\begin{align*}
\pi_1&=3-f_1^*-i_1^* \\
&=3-(\rho-p_1^*)+r_1^* \\
&=3-\rho+r_1^*(r_1^*+2)+r_1^*\\
&=3-\rho+r_1^{*2}+3r_1^*
\end{align*}

Also, recall that, under indemnity the inflation is 2\% in the first
period. This means we can calculate the potential \emph{deflationary
bias} in the first period without indemnity.

\begin{align*}
\pi_1(x=1)&=2 \\
\pi_1(x=0)-2&=\pi_1(x=0)-\pi_1(x=1) \\
&=r_1^{*2}(x=0)-r_1^{*2}(x=1)+3r_1^*(x=0)-3r_1^*(x=1)
\end{align*}

This is another major conclusion of this model:

\deflationary*
%random placeholder

Knowing the belief about distributions of \(\epsilon_{d2}\) and
\(\epsilon_{s2}\), we can calculate the believed distribution of \(u\):

\begin{align*}
\tilde\epsilon_{d2}& \sim U(-2,2) \\
\tilde\epsilon_{s2}& =0 \\
u&=2-\rho+\epsilon_{d2}-\epsilon_{s2} \\
&\sim U(-\rho, 4-\rho)
\end{align*}

This means the probability density \(u\) is
\(\frac{1}{(4-\rho)-(\rho)}=\frac{1}{4}\). Moreover, for an inflationary
pressure to be possible, an upper limit for \(\rho\) must also be set:

\begin{align}
4-\rho&>2\nonumber \\
\rho&<2 \nonumber\\
\rho&\in(1,2) \label{eq-rho-range}
\end{align}

Furthermore, in reality, the major central banks, even if they were not
indemnified, chose to adopt contractionary monetary policy amid
inflationary pressure, rather than maintaining a neutral stance to avoid
financial losses. In our model, this corresponds to the case where the
interest rate at the upper limit of \(u\) must be greater than 2:

\begin{align*}
i^*(x=0,u=4-\rho)&>2\\
2+\frac{\alpha\psi r_1}{2}&\leq4-\rho \\
\alpha\psi r_1&\leq4-2\rho \\
\alpha&\leq\frac{4-2\rho}{\psi r_1}
\end{align*}

Since the values of \(r_1^*(x=0)\) is not yet known, we have to further
restrict this constraint by setting \(r_1^*(x=0)\) to its theoretical
maximum of \(r_1^*(x=1)\), as per Proposition \ref{prp-prudence}:

\[
\alpha\leq\frac{4-2\rho}{\psi r_1^*(x=1)}
\]

With this constraint, we can now calculate the expected utility of the
central bank for the second period (\(EU_{B2}\)):

\begin{align*}
&EU_{B2}(x=0) \\
=&\int_{-\rho}^{2} U_{B2}(x=0,i_2<2) \cdot\frac{1}{4} \, du+ \int_{2}^{2+\frac{\alpha\psi r_1}{2}} U_{B2}(x=0,i_2=2) \cdot \frac{1}{4} \, du \\&+ \int_{2+\frac{\alpha\psi r_1}{2}}^{4-\rho} U_{B2}(x=0,i_2>2) \cdot \frac{1}{4} \, du\\
=&\int_{-\rho}^{2}0 \cdot \frac{1}{4} \, du+ \int_{2}^{2+\frac{\alpha\psi r_1}{2}}-(u-2)^2 \cdot \frac{1}{4} \, du \\&+ \int_{2+\frac{\alpha\psi r_1}{2}}^{4-\rho}[-(\frac{\alpha\psi r_1}{2})^2-\alpha\psi r_1(u-\frac{\alpha\psi r_1}{2}-2)] \cdot \frac{1}{4} \, du\\
=&\int_{-\rho}^{2}0 \cdot \frac{1}{4} \, du+ \int_{2}^{2+\frac{\alpha\psi r_1}{2}}-(u-2)^2 \cdot \frac{1}{4} \, du \\&+ \int_{2+\frac{\alpha\psi r_1}{2}}^{4-\rho}[\frac{(\alpha\psi r_1)^2}{4}-\alpha\psi r_1(u-2)] \cdot \frac{1}{4} \, du\\
=&[-\frac{(u-2)^3}{12}]_{2}^{2+\frac{\alpha\psi r_1}{2}}+[\frac{(\alpha\psi r_1)^2}{16}u-\alpha\psi r_1(\frac{u^2}{8}-\frac{u}{2})]_{2+\frac{\alpha\psi r_1}{2}}^{4-\rho}\\
=&-\frac{(\frac{\alpha\psi r_1}{2})^3}{12}+[\frac{(\alpha\psi r_1)^2}{16}u-\frac{\alpha\psi r_1 u}{8}(u-4)]_{2+\frac{\alpha\psi r_1}{2}}^{4-\rho}\\
=&-\frac{(\alpha\psi r_1)^3}{96}-[\frac{(\alpha\psi r_1)^2}{16}(2+\frac{\alpha\psi r_1}{2})-\frac{\alpha\psi r_1(2+\frac{\alpha\psi r_1}{2})}{8}(-2+\frac{\alpha\psi r_1}{2})]+[\frac{(\alpha\psi r_1)^2}{16}(4-\rho)+\frac{\alpha\psi r_1(4-\rho)}{8}\rho]\\
=&-\frac{(\alpha\psi r_1)^3}{96}-[\frac{(\alpha\psi r_1)^2}{16}(2+\frac{\alpha\psi r_1}{2})-\frac{\alpha\psi r_1(\frac{(\alpha\psi r_1)^2}{4}-4)}{8}]+[\frac{(\alpha\psi r_1)^2}{4}-\frac{(\alpha\psi r_1)^2}{16}\rho+\frac{\alpha\psi r_1 \rho}{2}-\frac{\alpha\psi r_1 \rho^2}{8}]\\
=&-\frac{(\alpha\psi r_1)^3}{96}-\frac{(\alpha\psi r_1)^2}{8}-\frac{(\alpha\psi r_1)^3}{32}+\frac{(\alpha\psi r_1)^3}{32}-\frac{\alpha\psi r_1}{2}+\frac{(\alpha\psi r_1)^2}{4}-\frac{(\alpha\psi r_1)^2}{16}\rho+\frac{\alpha\psi r_1 \rho}{2}-\frac{\alpha\psi r_1 \rho^2}{8}\\
=&-\frac{(\alpha\psi r_1)^3}{96}-\frac{(\alpha\psi r_1)^2}{8}+\frac{(\alpha\psi r_1)^2}{4}-\frac{(\alpha\psi r_1)^2}{16}\rho-\frac{\alpha\psi r_1}{2}+\frac{\alpha\psi r_1 \rho}{2}-\frac{\alpha\psi r_1 \rho^2}{8} \\
=&-\frac{(\alpha\psi r_1)^3}{96}+\frac{2-\rho}{16}(\alpha\psi r_1)^2+\frac{-4+4\rho-\rho^2}{8}\alpha\psi r_1
\end{align*} \begin{align*}
\frac{\partial}{\partial r_1}EU_{B2}(x=0)=&-\frac{(\alpha\psi )^3r_1^2}{32}+\frac{2-\rho}{8}(\alpha\psi)^2r_1+\frac{-4+4\rho-\rho^2}{8}\alpha\psi \\
\frac{\partial}{\partial r_1}EU_{B}(x=0)=&-\frac{(\alpha\psi )^3r_1^2}{32}+\frac{2-\rho}{8}(\alpha\psi)^2r_1+\frac{-4+4\rho-\rho^2}{8}\alpha\psi-2(1-\rho+\psi(r_1+2)r_1+r_1)=0\\
=&-\frac{(\alpha\psi )^3r_1^2}{32}+\frac{2-\rho}{8}(\alpha\psi)^2r_1+\frac{-(2-\rho)^2}{8}\alpha\psi-2+2\rho-2\psi r_1^2-4\psi r_1-2r_1=0\\
0=&(-\frac{(\alpha\psi )^3}{32}-2\psi)r_1^2+(\frac{2-\rho}{8}(\alpha\psi)^2-4\psi-2)r_1-\frac{(2-\rho)^2}{8}\alpha\psi-2+2\rho
\end{align*}

For the convenience of analytical results and to set a justifiable
domain for \(\alpha\) in later simulation, we constrain \(\alpha\) so
that the the expected utility of the bank (\(B\)) without indemnity is
concave in \(r_1\). This is equivalent to the condition that the partial
derivative above is decreasing in \(r_1\geq0\):

\begin{align*}
\frac{2-\rho}{8}(\alpha\psi)^2-4\psi-2&\leq0\\
\frac{2-\rho}{8}(\alpha\psi)^2&\leq4\psi+2\\
(\alpha\psi)^2&\leq\frac{8(4\psi+2)}{2-\rho}\\
0<\alpha&\leq\frac{\sqrt{\frac{8(4\psi+2)}{2-\rho}}}{\psi}
\end{align*}

This means that we can find an analytical solution for \(r_1\):

\begin{align*}
\bar r_1^*(x=0)=&\frac{(\frac{2-\rho}{8}(\alpha\psi)^2-4\psi-2)+\sqrt{(\frac{2-\rho}{8}(\alpha\psi)^2-4\psi-2)^2-2(\frac{(\alpha\psi)^3}{16}+4\psi)(\frac{(2-\rho)^2}{8}\alpha\psi+2-2\rho)}}{\frac{(\alpha\psi)^3}{16}+4\psi} \\
r_1^*(x=0)&=\begin{cases}
0~\text{if}~\bar r_1^*(x=0)\leq0\\
\bar r_1^*(x=0)~\text{if}~0<\bar r_1^*(x=0)<r_1^*(x=1) \\
r_1^*(x=1)~\text{if}~\bar r_1^*(x=0)\geq r_1^*(x=1)
\end{cases}
\end{align*}

Now we can calculate the utility of government (\(G\)) without indemnity
in period 1 (\(U_{G1}\)):

\begin{align*}
U_{G1}=&g_{1}=\pi_{1}\\
=&3-f_1-i_1\\
=&3-\rho+p_1+r_1\\
=&3-\rho+r_1-\psi(i_1-2)r_1\\
=&3-\rho+r_1+\psi(r_1+2)r_1\\
\end{align*}

We now calculate the expected utility of government (\(G\)) without
indemnity in period 2 (\(EU_{G2}\)). As previously demonstrated, the
government always chooses the same level of total fiscal surplus
(\(F=\rho\)). The variation in its utility therefore depends on the
level of real growth (\(g_2\)), which in our simplified model is
believed to equal the level of inflation (\(\tilde g_2=\tilde\pi_2\)).

\begin{figure}

\centering{

\begin{tikzpicture}
\begin{axis}[
    axis lines = left,
    width = 10cm,
    height = 7cm,
    xlabel = \(u\),
    ylabel = \(\tilde g_2{=}\tilde\pi_2\),
    legend pos=north west,
    legend cell align={left},
]
%Below the red parabola is defined
\tikzmath{\r1 = 0.08113883; \r0 =0.04667465; \a = 4;} 

\addplot [
    domain=1:2.75, 
    samples=100, 
    color=blue,
]
{2};

%Here the blue parabola is defined

\addplot [
    domain=1:2, 
    samples=100, 
    color=red,
    ]
    {2};
\addplot [
    domain=2:( 2+(\a * \r0)/2), 
    samples=100, 
    color=red,
]
{x};
\addplot [
    domain=( 2+(\a * \r0)/2):2.75, 
    samples=100, 
    color=red,
]
{2+(\a * \r0)/2};

\addplot[mark=none, black, thick, dotted] coordinates {(2,1.99) (2,2)};

% Add legend entries
\addlegendimage{color=blue,solid}
\addlegendentry{with indemnity}
\addlegendimage{color=red,solid}
\addlegendentry{without indemnity}

\end{axis}
\end{tikzpicture}

}

\caption{\label{fig-pi2-ana}Illustration of the perceived second-period
inflation and growth (\(\tilde g_2=\tilde\pi_2\)) with respect to \(u\)
(\(\alpha=4\), \(\rho=1.25\))}

\end{figure}%

As shown in Figure~\ref{fig-pi2-ana}, the growth and inflation rates are
kept at 2\% in the second period in case of deflationary pressure
(\(u\leq2\)). They rise with \(u\) when inflationary pressure is low
\(2<u\leq2+\frac{\alpha\psi r_1}{2}\); this corresponds to the scenario
when monetary policy (\(i\)) kept at 2 in Figure~\ref{fig-i0}. When
\(u>2+\frac{\alpha\psi r_1}{2}\), the growth and inflation rates are
kept at a constant level of \(2+\frac{\alpha\psi r_1}{2}\); this
corresponds to the scenario when monetary policy (\(i\)) rises up again
to tackle high inflationary pressure in Figure~\ref{fig-i0}.

This is referred to as the \emph{inflationary bias} in this paper.

\inflationary*
%random placeholder

As such, we can calculate the expected utility of government (\(G\))
without indemnity in period 2 (\(EU_{G2}\)):

\begin{align*}
EU_{G2}=&\int_{-s}^2 2\cdot \frac{1}{4}du+\int_{2}^{2+\frac{\alpha\psi r_1}{2}}u\cdot\frac{1}{4}du+\int_{2+\frac{\alpha\psi r_1}{2}}^{4-\rho}(2+\frac{\alpha\psi r_1}{2})\cdot\frac{1}{4}du\\
=&(1+\frac{1}{2}\rho)+[\frac{1}{8}u^2]_{2}^{2+\frac{\alpha\psi r_1}{2}}+[\frac{1}{2}u+\frac{\alpha\psi r_1u}{8}]_{2+\frac{\alpha\psi r_1}{2}}^{4-\rho}\\
=&(1+\frac{1}{2}\rho)+(\frac{1}{2}+\frac{\alpha\psi r_1}{4}+\frac{(\alpha\psi r_1)^2}{32}-\frac{1}{2})-(1+\frac{\alpha\psi r_1}{4}+\frac{\alpha\psi r_1}{4}+\frac{(\alpha\psi r_1)^2}{16})\\
&+(2-\frac{\rho}{2}+\frac{\alpha\psi r_1}{2}-\frac{\alpha\psi r_1}{8}\rho)\\
=&(1+\frac{1}{2}\rho)+(\frac{\alpha\psi r_1}{4}+\frac{(\alpha\psi r_1)^2}{32})-(1+\frac{\alpha\psi r_1}{2}+\frac{(\alpha\psi r_1)^2}{16})+(2-\frac{\rho}{2}+\frac{\alpha\psi r_1}{2}-\frac{\alpha\psi r_1}{8}\rho)\\
=&\frac{(\alpha\psi r_1)^2}{32}-\frac{(\alpha\psi r_1)^2}{16}+\frac{\alpha\psi r_1}{4}-\frac{\alpha\psi r_1}{2}+\frac{\alpha\psi r_1}{2}-\frac{\alpha\psi r_1}{8}\rho+1-1+2+\frac{1}{2}\rho-\frac{1}{2}\rho\\
=&-\frac{(\alpha\psi r_1)^2}{32}+\frac{\alpha\psi r_1}{4}-\frac{\alpha\psi r_1}{8}\rho+2
\end{align*}

Hence, the expected utility of government (\(G\)) without indemnity is:

\begin{align*}
EU_G(x=0)&=U_{G1}+EU_{G2}\\
&=3-\rho+r_1+\psi(r_1+2)r_1-\frac{(\alpha\psi r_1)^2}{32}+\frac{\alpha\psi r_1}{4}-\frac{\alpha\psi r_1}{8}\rho+2 \\
&=5-\rho+r_1+\psi(r_1+2)r_1-\frac{(\alpha\psi r_1)^2}{32}+\frac{\alpha\psi r_1}{4}-\frac{\alpha\psi r_1}{8}\rho
\end{align*}

\subsection{Decision to Indemnify}\label{decision-to-indemnify}

The government will indemnify if the expected utility of government with
indemnity is greater than the expected utility of government without
indemnity:

\[
x=\begin{cases}
1~\text{if}~ EU_G(x=1)>EU_G(x=0)\\
0~\text{otherwise}
\end{cases}
\]

\subsection{Further Details on Numerical
Evaluation}\label{further-details-on-numerical-evaluation}

This section describes the \hyperref[sec-simulation]{Numerical
Evaluation} process in detail. Note that we use \(\psi=1\) throughout
the evaluation.

We first calculate the risk levels under indemnity:

\begin{align*}
&r^*(x=1)=r^*_1(x=1)=r^*_2(x=1) \\
=&\frac{-(2\psi+1)+\sqrt{(2\psi+1)^2-4\psi(1-\rho)}}{2\psi} \\
\end{align*}

We then calculate the risk levels without indemnity:

\begin{align*}
\bar r_1^*(x=0)=&\frac{(\frac{2-\rho}{8}(\alpha\psi)^2-4\psi-2)+\sqrt{(\frac{2-\rho}{8}(\alpha\psi)^2-4\psi-2)^2-2(\frac{(\alpha\psi)^3}{16}+4\psi)(\frac{(2-\rho)^2}{8}\alpha\psi+2-2\rho)}}{\frac{(\alpha\psi)^3}{16}+4\psi} \\
r_1^*(x=0)&=\begin{cases}
0~\text{if}~\bar r_1^*(x=0)\leq0\\
\bar r_1^*(x=0)~\text{if}~0<\bar r_1^*(x=0)<r_1^*(x=1) \\
r_1^*(x=1)~\text{if}~\bar r_1^*(x=0)\geq r_1^*(x=1)
\end{cases}
\end{align*}

With this information, we are able to calculate the expected utilities
of the government with and without indemnity:

\begin{align*}
EU_G(x=1)&=4 \\
EU_G(x=0)&=5-\rho+r_1+\psi(r_1+2)r_1-\frac{(\alpha\psi r_1)^2}{32}+\frac{\alpha\psi r_1}{4}-\frac{\alpha\psi r_1}{8}\rho
\end{align*}

The government indemnifies the central bank if the expected utility from
doing so is greater:

\[ 
x=\begin{cases} 
1~\text{if}~ EU_G(x=1)>EU_G(x=0)\\ 
0~\text{otherwise} 
\end{cases} 
\]

We then calculate the relevant economic outcomes in period 1:

\begin{align*}
i_1(x=0)&=-r(x=0) \\
i_1(x=1)&=-r(x=1) \\
p_1(x=0)&=-\psi(i_1(x=0)-2)r(x=0) \\
p_1(x=1)&=-\psi(i_1(x=1)-2)r(x=1) \\
\pi_1(x=0)&=g_1(x=0)=3-(\rho-p_1(x=0))-i_1(x=0) \\
\pi_1(x=1)&=g_1(x=1)=2
\end{align*}

We then calculate the relevant economic outcomes in period 2:

\begin{align*}
i_2(x=0)&=\begin{cases}
2~\text{if}~4-\rho\leq2+\frac{\alpha\psi r(x=0)}{2}\\
4-\rho+\frac{\alpha\psi r(x=0)}{2}~\text{if}~4-\rho>2+\frac{\alpha\psi r(x=0)}{2}
\end{cases}\\
i_2(x=1)&=\frac{4-\rho+2\psi r(x=1)}{\psi r(x=1)+1} \\
p_2(x=0)&=-\psi(i_2(x=0)-2)r(x=0) \\
p_2(x=1)&=-\psi(i_2(x=1)-2)r(x=1) \\
\pi_2(x=0)&=6-\rho-i_2(x=0) \\
\pi_2(x=1)&=2 \\
g_2(x=0)&=\pi_2(x=0)-2 \\
g_2(x=1)&=\pi_2(x=1)-2
\end{align*}

\newpage

\section{More Information on Sample Selection}\label{sec-sample}

The following table discusses all countries in the European Union (EU)
and the Organisation for Economic Co-operation and Development (OECD),
which constitute the potential pool for the sample. The table provides
justification for the exclusion of certain countries from the sample of
the dataset.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\caption{List of EU and OECD countries and the reasons for
exclusion}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Country
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Inclusion
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Reason for exclusion
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Country
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Inclusion
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Reason for exclusion
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Australia & No & Late QE (2020) \\
Austria & Yes & \\
Belgium & Yes & \\
Bulgaria & No & No QE \\
Canada & No & Late QE (2020) \\
Chile & No & Late QE (2020) \\
Colombia & No & Late QE (2020) \\
Costa Rica & No & No QE \\
Croatia & No & Late QE (2020) \\
Cyprus & Yes & \\
Czech Republic & No & No QE \\
Denmark & No & No QE \\
Estonia & Yes & \\
Finland & Yes & \\
France & Yes & \\
Germany & Yes & \\
Greece & Yes & \\
Hungary & No & Late QE (2017) \\
Iceland & No & No QE \\
Ireland & Yes & \\
Israel & Yes & \\
Italy & Yes & \\
Japan & Yes & \\
Korea (Republic of) & No & No QE \\
Latvia & Yes & \\
Lithuania & Yes & \\
Luxembourg & Yes & \\
Malta & Yes & \\
Mexico & No & No QE \\
Netherlands & Yes & \\
New Zealand & No & Late QE (2020) \\
Norway & No & No QE \\
Poland & No & Late QE (2020) \\
Portugal & Yes & \\
Romania & No & Late QE (2020) \\
Slovak Republic & Yes & \\
Slovenia & Yes & \\
Spain & Yes & \\
Sweden & Yes & \\
Switzerland & No & Extreme effect of exchange rate on central bank
profit. See Reis (\citeproc{ref-Reis2015}{2015}). \\
Turkiye & No & Hyperinflation \\
United Kingdom & Yes & \\
United States & Yes & \\
\end{longtable}

\newpage

\section{List of Central Bank Financial Statement Data
Sources}\label{sec-source}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 2\tabcolsep) * \real{0.3750}}
  >{\raggedright\arraybackslash}p{(\linewidth - 2\tabcolsep) * \real{0.6250}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Country
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Financial statement source(s) for manual collection
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Austria &
\url{https://www.oenb.at/en/Publications/Oesterreichische-Nationalbank/Annual-Report.html} \\
Belgium &
\url{https://www.nbb.be/en/publications-and-research/economic-and-financial-publications/annual-reports} \\
Cyprus &
\url{https://www.centralbank.cy/en/publications/annual-report} \\
Estonia &
\url{https://www.eestipank.ee/en/publications/annual-report} \\
Finland &
\url{https://www.suomenpankki.fi/en/media-and-publications/publications/annual-report/} \\
France &
\url{https://www.banque-france.fr/en/publications-and-research/our-main-publications/annual-reports} \\
Germany &
\url{https://www.bundesbank.de/en/publications/reports/annual-reports} \\
Greece &
\url{https://www.bankofgreece.gr/en/news-and-media/financial-statements/annual-accounts} \\
Ireland &
\url{https://www.centralbank.ie/publication/corporate-reports/annual-reports} \\
Israel &
\url{https://www.boi.org.il/en/communication-and-publications/regular-publications/bank-of-israel-annual-report/} \\
Italy &
\url{https://www.bancaditalia.it/pubblicazioni/relazione-annuale/index.html?com.dotmarketing.htmlpage.language=1} \\
Japan & None (all data are from S\&P Capital IQ Pro) \\
Latvia &
\url{https://www.bank.lv/en/about-us/operations/annual-reports} \\
Lithuania &
\url{https://www.lb.lt/en/reviews-and-publications/category.38/series.204} \\
Luxembourg &
\url{https://www.bcl.lu/en/publications/Annual-reports/index.html} \\
Malta & \url{https://www.centralbankmalta.org/annual-reports} \\
Netherlands & None (the data from the
\href{https://www.dnb.nl/en/publications/publications-dnb/?p=1&l=10&pt=MTgxODg}{DNB
website} are even more incomplete than S\&P Capital IQ Pro) \\
Portugal &
\url{https://www.bportugal.pt/en/page/list-publications-banco-de-portugal} \\
Slovak Republic & \url{https://nbs.sk/en/publications/annual-report/} \\
Slovenia &
\url{https://www.bsi.si/en/publications/annual-reports/banka-slovenijes-annual-report} \\
Spain &
\url{https://www.bde.es/wbe/en/publicaciones/informes-memorias-anuales/informe-anual/informe-anual-2010.html} \\
Sweden &
\url{https://www.riksbank.se/en-gb/press-and-published/publications/annual-report/} \\
United Kingdom &
\url{https://www.bankofengland.co.uk/news/publications} \\
United States &
\url{https://www.federalreserve.gov/aboutthefed/audited-annual-financial-statements.htm} \\
\end{longtable}

\newpage

\section{Placebo Test of Pre-treatment Trends}\label{sec-pretrend}

As mentioned in the \hyperref[sec-empirical]{Empirical Strategy}
section, a placebo test of pre-treatment trends commonly serves as
diagnostics for potential violation of assumptions among the family of
SCM-inspired estimators. The idea is akin to the test of parallel
pre-treatment trends for the difference-in-differences (DiD) design.

To this end, the pre-treatment period (1999-2008) is divided into two
parts by the \emph{placebo} treatment date of 2004. The DM-LFM is
trained on data before 2004 and expected to predict the outcomes (BoE
profit as percentage of UK GDP) between 2004 and 2008. A null result
should be found for the placebo ATT, otherwise violations of the DM-LFM
model assumptions are likely which would invalidate our main results.

Similar to the main \hyperref[sec-results]{results}, results for
estimations with and without covariates are reported in
Table~\ref{tbl-pretrend}. The predicted and actual trends of BoE profits
from the placebo estimation with covariates are visualised in
Figure~\ref{fig-pretrend}. It can be seen that the placebo ATT is close
to zero (-0.05) and statistically very insignificant (\(p= 0.57\)). We
should therefore be more confident in the validity of our main analysis
results.

\begin{table}[H]

\caption{\label{tbl-pretrend}Results for DM-LFM analysis of placebo
impact of indemnity on BoE profits}

\centering{

\centering
\begin{talltblr}[         %% tabularray outer open
entry=none,label=none,
note{}={+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001},
note{ }={95\% equal-tailed Credible Intervals in square brackets.},
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]},
hline{2}={1-3}{solid, black, 0.05em},
hline{10}={1-3}{solid, black, 0.05em},
hline{1}={1-3}{solid, black, 0.1em},
hline{13}={1-3}{solid, black, 0.1em},
column{2-3}={}{halign=c},
column{1}={}{halign=l},
}                     %% tabularray inner close
& (1) & (2) \\
ATT & \num{-0.031} & \num{-0.057} \\
& [\num{-0.223}, \num{0.160}] & [\num{-0.260}, \num{0.148}] \\
Publicly traded &  & \num{0.000} \\
&  & [\num{-0.008}, \num{0.011}] \\
Euro Area &  & \num{-0.003} \\
&  & [\num{-0.019}, \num{0.008}] \\
Reappointability &  & \num{-0.000} \\
&  & [\num{-0.016}, \num{0.016}] \\
Observations & \num{226} & \num{226} \\
Treated Units & \num{1} & \num{1} \\
Control Units & \num{22} & \num{22} \\
\end{talltblr}

}

\end{table}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-pretrend-1.pdf}}

}

\caption{\label{fig-pretrend}Estimated counterfactual and actual trends
of BoE profits as \% of UK GDP (placebo treatment at 2004)}

\end{figure}%

\newpage

\section{DM-LFM MCMC Diagnostics}\label{sec-mcmc-diag}

Due to the complexity of the Bayesian estimation of the DM-LFM, the
estimator relies on Markov Chain Monte Carlo (MCMC) algorithm to
approximate the posterior distribution of the ATT for inference. This
appendix provides diagnostic information on the Maokov Chain Monte Carlo
draws. Table~\ref{tbl-mcmc-sum} shows the summary statistics for the
ATTs in the deflationary and inflationary periods;
Table~\ref{tbl-mcmc-quant} show the corresponding quantiles.
Figure~\ref{fig-traceplot-def} and Figure~\ref{fig-traceplot-inf} trace
the simulation draws. It can be seen from these figures that there is no
serious serial correlation that concerns further thinning.
Figure~\ref{fig-densplot-def} and Figure~\ref{fig-denseplot-inf} plot
the distribution density of such draws. It can be seen that the draws
are normally shaped, which implies that we can be confident that they
are good approximations of the target distributions.

\begin{table}[H]

\caption{\label{tbl-mcmc-sum}Summary table of DM-LFM MCMC draws for ATT}

\centering{

\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{l|l|l|r|r|r|r}
\hline
Period & Start year & End year & Mean & SD & Naive SE & Time-series SE\\
\hline
Deflationary & 2009 & 2021 & 0.391988 & 0.144423 & 0.001444 & 0.002835\\
\hline
Inflationary & 2022 & 2023 & -0.707911 & 0.266830 & 0.002668 & 0.004027\\
\hline
\end{tabular}}

}

\end{table}%

\begin{table}[H]

\caption{\label{tbl-mcmc-quant}Quantiles of DM-LFM MCMC draws for ATT}

\centering{

\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{l|l|l|r|r|r|r|r}
\hline
Period & Start year & End year & 2.5\% & 25\% & 50\% & 75\% & 97.5\%\\
\hline
Deflationary & 2009 & 2021 & 0.104079 & 0.295288 & 0.391682 & 0.489288 & 0.673773\\
\hline
Inflationary & 2022 & 2023 & -1.236136 & -0.881064 & -0.706616 & -0.533039 & -0.182563\\
\hline
\end{tabular}}

}

\end{table}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-traceplot-def-1.pdf}}

}

\caption{\label{fig-traceplot-def}Trace plot for ATT MCMC simulations
(Deflationary period 2009-2021).}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-traceplot-inf-1.pdf}}

}

\caption{\label{fig-traceplot-inf}Trace plot for ATT MCMC simulations
(Inflationary period 2022-2023).}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-densplot-def-1.pdf}}

}

\caption{\label{fig-densplot-def}Density plot for ATT MCMC simulations
(Deflationary period 2009-2021).}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-denseplot-inf-1.pdf}}

}

\caption{\label{fig-denseplot-inf}Density plot for ATT MCMC simulations
(Inflationary period 2022-2023).}

\end{figure}%

\newpage

\section{Results with Alternative Estimators}\label{sec-alternative}

This section replicates the main \hyperref[sec-results]{results} with
alternative estimators as robustness checks. The selected estimators are
all designed for estimating the effect of a binary treatment with panel
data, hence potential alternatives to the DM-LFM. In addition to the
familiar difference-in-differences (DiD) estimator first employed by
Card \& Krueger (\citeproc{ref-Card2000}{2000}) and the Synthetic
Control Method (SCM) proposed by Abadie \& Gardeazabal
(\citeproc{ref-Abadie2003}{2003}), we also use the synthetic
difference-in-differences estimator that combines the desirable
characteristics of the two (\citeproc{ref-Arkhangelsky2021}{Arkhangelsky
et al., 2021}). However, none of the three estimators provides valid
inference as pointed out by Pang et al. (\citeproc{ref-Pang2021}{2021}).
Therefore, one should pay more attention to the point estimates of the
Average Treatment Effect on the Treated (ATT) rather than the \(p\)
values. The results are shown in Table~\ref{tbl-alt} alongside the main
DM-LFM results with covariates from Columns (2) and (4) of
Table~\ref{tbl-main}. A comparison of the estimated treatment effects
over time by estimator is visualised in Figure~\ref{fig-alt}.

Please note that the three alternative estimators have smaller
observations and do not include covariates because the R
package\footnote{see Arkhangelsky (\citeproc{ref-R-synthdid}{2023}).}
used for their estimations do not support such features. For the SDiD
estimates, \(p\) values are generated using the placebo variance
estimation\footnote{See Algorithm 4 of Arkhangelsky et al.
  (\citeproc{ref-Arkhangelsky2021}{2021}).}, which tend to under-reject
the null hypothesis. For the DiD estimates, \(p\) values are calculated
using clustered standard errors, which tend to over-reject. For the SCM,
the permutation test \(p\) values are reported\footnote{see Abadie
  (\citeproc{ref-Abadie2021}{2021}) for further details on the
  permutation inferential procedure.}.

\begin{table}[H]

\caption{\label{tbl-alt}Results with alternative estimators for the
impact of indemnity on BoE profits}

\centering{

\centering
\begin{talltblr}[         %% tabularray outer open
entry=none,label=none,
note{}={+ p \num{< 0.1}, * p \num{< 0.05}, ** p \num{< 0.01}, *** p \num{< 0.001}},
note{ }={$p$ values are reported in parentheses.},
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]},
hline{2}={1-5}{solid, black, 0.05em},
hline{6}={1-5}{solid, black, 0.05em},
hline{1}={1-5}{solid, black, 0.1em},
hline{9}={1-5}{solid, black, 0.1em},
column{2-5}={}{halign=c},
column{1}={}{halign=l},
}                     %% tabularray inner close
& SDiD & DiD & SCM & DM-LFM \\
$ATT^\text{def}$ & \num{0.419} & \num{0.409}*** & \num{0.435} & \num{0.392}** \\
& (\num{0.220}) & (\num{<0.001}) & (\num{0.143}) & (\num{0.009}) \\
$ATT^\text{inf}$ & \num{-0.559} & \num{-0.516}** & \num{-0.653}+ & \num{-0.708}* \\
& (\num{0.293}) & (\num{0.003}) & (\num{0.095}) & (\num{0.010}) \\
Observations & \num{504} & \num{504} & \num{504} & \num{586} \\
Treated Units & \num{1} & \num{1} & \num{1} & \num{1} \\
Control Units & \num{20} & \num{20} & \num{20} & \num{23} \\
\end{talltblr}

}

\end{table}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-alt-1.pdf}}

}

\caption{\label{fig-alt}Estimated effects of indemnity on BoE profits by
estimator}

\end{figure}%

\newpage

\section{Results with Early Treatment}\label{sec-early}

This appendix replicates the main \hyperref[sec-results]{results} but
bring forwards the time of treatment from 2009 to 2004 to examine the
sensitivity of the results to potential anticipation effects and the
GFC. The results are shown in contrast to the original in
Table~\ref{tbl-early}. It can be seen that the point estimates remain
largely the same but the estimated effects of the indemnity on profits
lose their statistical significance at 5\%. This is likely due to the
lost information between 2006 and 2008 and a short pre-treatment period
of 5 years (1999-2003), which limit the precision of the estimates. The
stable point estimates should be sufficient to prove the robustness of
our main results.

\begin{table}[H]

\caption{\label{tbl-early}Results with early treatment (2005) for the
impact of indemnity on BoE profits}

\centering{

\centering
\resizebox{\ifdim\width>\linewidth 1\linewidth\else\width\fi}{!}{
\begin{talltblr}[         %% tabularray outer open
entry=none,label=none,
note{}={+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001},
note{ }={95\% equal-tailed Credible Intervals in square brackets.},
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]},
hline{2}={5}{solid, black, 0.05em},
hline{3}={1-5}{solid, black, 0.05em},
hline{11}={1-5}{solid, black, 0.05em},
hline{2}={2,4}{solid, black, 0.05em, l=-0.5},
hline{2}={3}{solid, black, 0.05em, r=-0.5},
hline{1}={1-5}{solid, black, 0.1em},
hline{14}={1-5}{solid, black, 0.1em},
column{3,5}={}{halign=c},
cell{1}{1}={}{halign=c},
cell{1}{2}={c=2}{halign=c},
cell{1}{4}={c=2}{halign=c},
cell{2-13}{1}={}{halign=l},
cell{2-13}{2}={}{halign=c},
cell{2-13}{4}={}{halign=c},
}                     %% tabularray inner close
& Deflationary (2009-2021) &  & Inflationary (2022-2023) &  \\
& Early & Original & Early  & Original  \\
ATT & \num{0.342}+ & \num{0.392}** & \num{-0.778}+ & \num{-0.708}* \\
& [\num{-0.037}, \num{0.725}] & [\num{0.107}, \num{0.679}] & [\num{-1.547}, \num{0.003}] & [\num{-1.238}, \num{-0.185}] \\
Publicly traded & \num{0.001} & \num{0.001} & \num{-0.003} & \num{-0.003} \\
& [\num{-0.006}, \num{0.011}] & [\num{-0.006}, \num{0.010}] & [\num{-0.030}, \num{0.014}] & [\num{-0.031}, \num{0.013}] \\
Euro Area & \num{0.000} & \num{0.000} & \num{-0.004} & \num{-0.003} \\
& [\num{-0.007}, \num{0.009}] & [\num{-0.007}, \num{0.009}] & [\num{-0.027}, \num{0.012}] & [\num{-0.024}, \num{0.013}] \\
Reappointability & \num{0.000} & \num{0.000} & \num{-0.001} & \num{-0.000} \\
& [\num{-0.004}, \num{0.006}] & [\num{-0.004}, \num{0.005}] & [\num{-0.013}, \num{0.010}] & [\num{-0.012}, \num{0.009}] \\
Observations & \num{586} & \num{586} & \num{586} & \num{586} \\
Treated Units & \num{1} & \num{1} & \num{1} & \num{1} \\
Control Units & \num{23} & \num{23} & \num{23} & \num{23} \\
\end{talltblr}
}

}

\end{table}%

\section{Additional Plots for the Supplementary Tests}\label{sec-supp}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-supp-ir-1.pdf}}

}

\caption{\label{fig-supp-ir}Estimated counterfactual and actual trends
of BoE policy interest rate}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{BailoutCB_files/figure-pdf/fig-supp-bs-1.pdf}}

}

\caption{\label{fig-supp-bs}Estimated counterfactual and actual trends
of BoE liabilities}

\end{figure}%

\begin{comment}
%TC:endignore
\end{comment}




\end{document}
